### ISSUE TITLE
not work in IOS

### ISSUE THREAD

**Issue by Xerosge** [matteobortolazzo/HtmlLabelPlugin#1]
Hi, I try using the plugin, i follow the steps, in android work fine, but in IOs don't work

I add the nuget in project and client follow the instructions

in appdelegate.cs i have:

`public override bool FinishedLaunching(UIApplication app, NSDictionary options)
		{
			HtmlLabelRenderer.Initialize();

			global::Xamarin.Forms.Forms.Init();

			LoadApplication(new App());

			return base.FinishedLaunching(app, options);
		}`

in "global::Xamarin.Forms.Forms.Init();" give me this error when lauch: 

System.TypeLoadException Could not load type Plugin.HtmlLabel.HtmlLabel, Plugin.HtmlLabel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)

Im new in Xamarin and C#, as said before in android work all ok

I hope can help me
S2

**Comment by matteobortolazzo** [comment]
So, I just uploaded a new version. There was a problem with the Nuget package. I created a new project and installed version [1.0.3](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/1.0.3) and everything works. Let me know.

**Comment by Xerosge** [comment]
With the new version all work ok!   Great job

**Comment by matteobortolazzo** [comment]
Great!
