### ISSUE TITLE
Linking issue for iOS

### ISSUE THREAD

**Issue by IeuanWalker** [matteobortolazzo/HtmlLabelPlugin#109]
Hi, I'm getting the following error when creating an AdHoc build.

Changing the linker behaviour from 'Link Framework SDKs only' to 'Don't Link', fixes the issue (but obviously not ideal)

NuGet version: 5 alpha 2

```
Severity Code Description Project File Line Suppression State Error Can't resolve the reference 'Xamarin.Forms.Core.FontFile', referenced from the method 'System.String LabelHtml.Forms.Plugin.iOS.FontExtensions::CleanseFontName(System.String)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. CardiffMobileApp.iOS
```

**Comment by matteobortolazzo** [comment]
Hi,

you created 5.2 NuGet. I have no idea why of the linking issue, it never happened before.

Can you please try to regenerate the package and test it before send it to me (alpha 3)?

Unfortunately I cannot do that myself.

Try to clone this repo and just check "Generate NuGet on Build" in Release mode maybe.

**Comment by bares43** [comment]
Hi, same problem here. It happened with Xamarin Forms 4.7. With 4.5 it was ok.

**Comment by bares43** [comment]
I think it's because of this usage https://github.com/matteobortolazzo/HtmlLabelPlugin/blob/v5/src/HtmlLabel/iOS/Extensions.cs#L156 of `FontFile` here. It's referenced from namespace `Xamarin.Forms.Core` but it moved to namespace `Xamarin.Forms` in XF https://github.com/xamarin/Xamarin.Forms/issues/10495

**Comment by IeuanWalker** [comment]
@bares43 Are you having and issue with version 5 alpha 2 too?

If you are it's probably my fault, think i may have create the package in debug rather than Release mode, havnt had time to test yet sorry.

**Comment by bares43** [comment]
@IeuanWalker  I'm not sure where I can get version 5 alpha 2. I can see only alpha 1 on Nuget. However, I think that it still will be an issue, since it's in source code (latest commit in branch v5).

**Comment by IeuanWalker** [comment]
@bares43 you are right.

I needed to update the Xamarin.forms NuGet to version 4.6.0.847.
Anything lower than that has an issue with the linker do to the method being moved.

@matteobortolazzo you ok if I do a PR to update the Xamarin.Forms version. Current version 5 is unusable on app that is on XF version 4.6.0.847 or above

**Comment by matteobortolazzo** [comment]
@IeuanWalker sure, create a PR, and I will merge it in v5

**Comment by matteobortolazzo** [comment]
I still cannot work on this and there are a lot of issues open so I lost track of everything that is going on

**Comment by IeuanWalker** [comment]
@matteobortolazzo cool no problem. We are using this package quite a bit in our app, so happy to help maintain it :)

**Comment by matteobortolazzo** [comment]
Thanks, man :) I will be back soon, hopefully by the end of the week

**Comment by matteobortolazzo** [comment]
@IeuanWalker it took me a lot of time but I am back, now I can work on this project again! If v5 is stable I will fix the other issues on top of that

**Comment by IeuanWalker** [comment]
@IeuanWalker awesome.

I'd say it is, we released a new version of are app 2 weeks ago, and passed all our testing :)

**Comment by matteobortolazzo** [comment]
@IeuanWalker I noticed there's a bit of padding now, can we do anything about it? Also you mind send me a brief description of what you did with the iOS render so I can get up to speed? Or a call

**Comment by IeuanWalker** [comment]
@matteobortolazzo Only things I've done in this library is updated XF library and fixed a null exception for email links (#108).
In our app iOS and android looks identical, when I have some time ill get some screenshots.

**Comment by matteobortolazzo** [comment]
Well, you replaced the renderer for v5 right?

**Comment by IeuanWalker** [comment]
@matteobortolazzo sorry nope that wasnt me. 
The only 2 PRs I've done are -
- #109
- #108

Looks like @DaanKwilia did the iOS renderer in this PR #104
