### ISSUE TITLE
.net standard 1.3 support

### ISSUE THREAD

**Issue by Arbalets** [matteobortolazzo/HtmlLabelPlugin#11]
Hi, nice plugin. 
What about supporting .net standard 1.3 as well? I tried to run your source against it, doesn't seem to break anything.

**Comment by matteobortolazzo** [comment]
Ok I'll check and I'll eventually release an update

**Comment by matteobortolazzo** [comment]
Ok seems it works, next release will support 1.3

**Comment by matteobortolazzo** [comment]
Done in [2.1.1](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.1.1)

**Comment by Arbalets** [comment]
Thanks.

**Comment by Arbalets** [comment]
Cannot install it, nuget package is still targeting .net standard 2.0 only.

**Comment by matteobortolazzo** [comment]
Maybe is the Xamarin.Forms min version, the package targets 2.5.0 what version are you using?

**Comment by Arbalets** [comment]
No, I'm using the latest version:
![image](https://user-images.githubusercontent.com/4578695/35502848-f6af3fc2-04e6-11e8-8b01-9b5d47cc5d68.png)

**Comment by matteobortolazzo** [comment]
I don't know why. The [project ](https://github.com/matteobortolazzo/HtmlLabelPlugin/blob/master/src/Plugin.HtmlLabel/Plugin.HtmlLabel.csproj) targets 1.3

**Comment by Arbalets** [comment]
The problem seems to be the nuget package itself: 
![image](https://user-images.githubusercontent.com/4578695/35503424-bfbf8696-04e8-11e8-8067-59fe80dcf244.png)

**Comment by Arbalets** [comment]
It's nuget packages problem

**Comment by matteobortolazzo** [comment]
You're right, I'll update the package now, thanks

**Comment by matteobortolazzo** [comment]
[Here 2.1.2](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.1.2)

**Comment by matteobortolazzo** [comment]
But why use 1.3 if you have the latest Xamarin.Forms?

**Comment by Arbalets** [comment]
Can't go up just yet. I have plugins which are not compatible with the .netstandard 2.0.

**Comment by Arbalets** [comment]
Thanks, the problem is solved.
