### ISSUE TITLE
Mailto: links crash the apps if the link does not contain 'subject' and 'body' properties.

### ISSUE THREAD

**Issue by vhugogarcia** [matteobortolazzo/HtmlLabelPlugin#114]
**Steps to reproduce the issue on iOS:**
1. Create a link without **subject** and **body** properties.
2. Run the application and tap on a **mailto** link type.
3. The app will crash.

**Additional Information**
`public static string GetFirst(this Dictionary<string, List<string>> qParams, string key) =>`

The method above should return string.empty instead of null, due to sometimes the links may have or not a subject or body property.

**Comment by matteobortolazzo** [comment]
Hi, sorry I wasn't able to work on this in the last months.
Now I am back.
This is the code
```csharp
var message = new EmailMessage
{
To = new List<string> { to },
Subject = qParams.GetFirst("subject") ?? string.Empty,
Body = qParams.GetFirst("body") ?? string.Empty,
Cc = qParams.Get("cc") ?? new List<string>(),
Bcc = qParams.Get("bcc") ?? new List<string>()
};
```
so it is already defaulted to empty string.

Unfortunatly I don't have a real iOS device to test what is wrong, but I think it's Xamarin Essentials

**Comment by matteobortolazzo** [comment]
Sorry I just noticed I has been fixed in a PR for v5 :)

**Comment by matteobortolazzo** [comment]
v5 Released
