### ISSUE TITLE
HorizontalTextAlignment="center" along with LineHeight="2" applies LineHeight but aligns label to left side instead of center

### ISSUE THREAD

**Issue by PayalBhuva17** [matteobortolazzo/HtmlLabelPlugin#115]
Hello,

I am using the latest version of Xamarin.Forms(4.8.0.1269) and the latest version of Xam.Plugin.HtmlLabel(4.1.3).
The issue here is if I apply both HorizontalTextAlignment="Center" and LineHeight="1.4" to an HtmlLabel then it applies LineHeight but aligns label to the left side instead of center.

Below is the code:

<htmlLabel:HtmlLabel   Text="{Binding LoginDescription}" Margin="0,10,0,0"  Style="{StaticResource LabelPageContentStyle}" LineHeight="1.4" HorizontalTextAlignment="Center" HorizontalOptions="CenterAndExpand" VerticalOptions="Center" LineBreakMode="WordWrap" XAlign="Center" FontSize="Default"  />

Expected Result:
Both LineHeight and HorizontalTextAlignment should get applied to a HtmlLabel

**Comment by matteobortolazzo** [comment]
Hello,

I tested it in v5 (alpha) and it seems to work :)

I will be released in next days

**Comment by matteobortolazzo** [comment]
v5 Released
