### ISSUE TITLE
Bulleted input data shows extra character

### ISSUE THREAD

**Issue by divyesh008** [matteobortolazzo/HtmlLabelPlugin#117]
I have used Syncfusion's RichTextEditor in my application. To convert that input in simple text and show in app I have used HtmlLabelPlugin. 

When I create a bulleted list it shows with extra question mark "?"  character which I have not inserted. 

**Check this video for more detail:**
[https://www.dropbox.com/s/d28zr8ovbwcnng2/Screen%20Recording%202020-09-10%20at%2012.51.03%20PM.mov?dl=0](url)

**Comment by matteobortolazzo** [comment]
No follow-up, closing this
