### ISSUE TITLE
Custom Scheme Tel: not working when number has spaces

### ISSUE THREAD

**Issue by oridotaoyebode** [matteobortolazzo/HtmlLabelPlugin#118]
When a tel: custom scheme has  spaces between the phone numbers, the phone dialer doesn't open on Android

For example

`<p>Deslin - <a href=\"tel:0631595663\">063 1595 663</a></p> - Works`
`<p>Deslin - <a href=\"tel:063 159 5663\">063 1595 663</a></p> - Does  not work. `

The same HTML works on IOS but not on Android.

**Comment by matteobortolazzo** [comment]
Hi, the plugin uses Xamarin Essential so I cannot do much
[xamarin/essentials/phone-dialer](https://docs.microsoft.com/en-us/xamarin/essentials/phone-dialer?context=xamarin%2Fandroid&tabs=android)

**Comment by oridotaoyebode** [comment]
I submitted a PR for this 

https://github.com/matteobortolazzo/HtmlLabelPlugin/pull/120

**Comment by matteobortolazzo** [comment]
v5 Released
