### ISSUE TITLE
Style not working (android)

### ISSUE THREAD

**Issue by muhammetsahin** [matteobortolazzo/HtmlLabelPlugin#12]
Hi, 

I've just write simple text but style is not working (android). ios is okey

`<p><span style="text-decoration: underline;">Test</span> <span style="color: #3366ff;">deneme</span></p>`

`  <htmlLabel:HtmlLabel
          HorizontalOptions="FillAndExpand"
          HorizontalTextAlignment="Start"
          IsHtml="True"
          LineBreakMode="WordWrap"
          Text="{Binding Description"
          TextColor="{StaticResource TextColor}" />`

![image](https://user-images.githubusercontent.com/2045788/35186316-2eb793c6-fe23-11e7-92cd-f57189385e39.png)

**Comment by matteobortolazzo** [comment]
Hi sorry for the late answer, it's very strange I'll check

**Comment by matteobortolazzo** [comment]
So, the color style work on android the underline no, but that's an Android issue.
You can underline an element using the "<u>text</u>" tag
