### ISSUE TITLE
Navigation event Cancel not working.

### ISSUE THREAD

**Issue by tteglas** [matteobortolazzo/HtmlLabelPlugin#122]
Cancel on the Navigating event doesn't work. Browser is still opened even if Cancel = true;

The following line raised my suspicion, but not 100% sure if this is the issue:
```
label.SendNavigating(args);

			if (args.Cancel)
			{
				return;
			}
```

**Comment by somoreingold** [comment]
Same here. Maybe it's because args is passed by value instead of reference into SendNavigating, so it's never actually changed?

**Comment by somoreingold** [comment]
I take that back. this seems to only happen on Android.

**Comment by matteobortolazzo** [comment]
Sorry for the late answer, it's still strange that it's not working in Android. I will give a look

**Comment by matteobortolazzo** [comment]
@tteglas @somoreingold  So, the code is shared between iOS and Android. The Event is a class so it is passed by reference, and it works on my Samsung S10+. So I close this. (I am testing with v5 but it should be the same)

**Comment by tteglas** [comment]
@matteobortolazzo no worries, you didn't answer late :)
To my knowledge you have to explicitly pass by reference (using "ref" keyword), because even though it's reference type (all objects are), you're not changing that particular object reference's properties. Once the execution enters the method, you're changing properties on the object declared as input parameter of that method and not on the object declared before the method.

**Comment by matteobortolazzo** [comment]
No, value type fields of a class are still in the heap, "inside" the object. So when you pass the reference of a class and you change the value of a field, the field is changed inside the object. What you say is true for `struct`, where the object is copied unless you use the ref `keywork`. You can test this with ease, also, it's working for iOS and my Samsung, and the code is shared.

**Comment by tteglas** [comment]
I can only agree with you. I came across with some string manipulation I had to do and I found that I needed to pass my string using "ref" in order to achieve what I wanted. That somehow confused me in this matter.
Thank you for your answers.

**Comment by matteobortolazzo** [comment]
No worries :)
