### ISSUE TITLE
Opening links causes crashes with Pixels running Android 11

### ISSUE THREAD

**Issue by 4one4** [matteobortolazzo/HtmlLabelPlugin#129]
As near as I can tell, it only happens on Pixel phones running Android 11. When tapping on a link being displayed by the control, the app crashes. Other phones running Android 11 or Pixel phones running <11 seem to function just fine. Please let me know if there is any more information you need.

Thanks!

I believe this is the relevant portion of the debug log:
FATAL EXCEPTION: main 02-17 19:40:44.395 E/AndroidRuntime( 2840): Process: com.XXX.XXXXXXXXXX, PID: 2840 02-17 19:40:44.395 E/AndroidRuntime( 2840): android.runtime.JavaProxyThrowable: Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported. 02-17 19:40:44.395 E/AndroidRuntime( 2840): at Xamarin.Essentials.Browser.PlatformOpenAsync (System.Uri uri, Xamarin.Essentials.BrowserLaunchOptions options) [0x00164] in <0549689b1e8c45f5a913fb886b2b792e>:0 02-17 19:40:44.395 E/AndroidRuntime( 2840): at Xamarin.Essentials.Browser.OpenAsync (System.Uri uri, Xamarin.Essentials.BrowserLaunchOptions options) [0x00006] in <0549689b1e8c45f5a913fb886b2b792e>:0 02-17 19:40:44.395 E/AndroidRuntime( 2840): at LabelHtml.Forms.Plugin.Abstractions.UriExtensions.LaunchBrowser (System.Uri uri, Xamarin.Essentials.BrowserLaunchOptions options) [0x0000b] in <88ec9912dc0947618d5d428dbc97b5ac>:0 02-17 19:40:44.395 E/AndroidRuntime( 2840): at LabelHtml.Forms.Plugin.Abstractions.RendererHelper.HandleUriClick (LabelHtml.Forms.Plugin.Abstractions.HtmlLabel label, System.String url) [0x00047] in <88ec9912dc0947618d5d428dbc97b5ac>:0 02-17 19:40:44.395 E/AndroidRuntime( 2840): at LabelHtml.Forms.Plugin.Droid.HtmlLabelRenderer+HtmlLabelClickableSpan.OnClick (Android.Views.View widget) [0x00011] in <88ec9912dc0947618d5d428dbc97b5ac>:0 02-17 19:40:44.395 E/AndroidRuntime( 2840): at Android.Text.Style.ClickableSpan.n_OnClick_Landroid_view_View_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_widget) [0x0000f] in <4afaca695c944983bad26f02509cfe0a>:0 02-17 19:40:44.395 E/AndroidRuntime( 2840): at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.181(intptr,intptr,intptr) 02-17 19:40:44.395 E/AndroidRuntime( 2840)

**Comment by matteobortolazzo** [comment]
Hi, this looks like a bug with https://github.com/xamarin/essentials

**Comment by 4one4** [comment]
Thanks for the prompt reply. I will pursue it with them!
