### ISSUE TITLE
<br> tag in UWP

### ISSUE THREAD

**Issue by heatgithub** [matteobortolazzo/HtmlLabelPlugin#13]
I tested your code, but it didn't suited my needs, but I found one thing that didn't worked for me.
The `<br>` tag didn't work for me in a UWP project. The `var element = XElement.Parse(modifiedText);` line in the HtmlTextBehavior.cs file needs tags with starting and ending tags.
I solved it with this extra line:
`modifiedText = Regex.Replace(modifiedText, "<br>", "<br></br>", RegexOptions.IgnoreCase);`

**Comment by matteobortolazzo** [comment]
Hi, thanks you for the help, you can do a pull request if you want or I'll add your code soon :)

**Comment by matteobortolazzo** [comment]
Ok added to my code, thanks again
