### ISSUE TITLE
Left margin list tag (ul, li)

### ISSUE THREAD

**Issue by scriptBoris** [matteobortolazzo/HtmlLabelPlugin#133]
How change default left margin fot "list tag"?

What it looks like by default:
![image](https://user-images.githubusercontent.com/29772096/130215398-21addae1-a65e-4ded-ba72-7629e75862a8.png)

How it should look
![image](https://user-images.githubusercontent.com/29772096/130215497-a34a3dad-993a-4963-9f64-2b86420ed3a4.png)

**Comment by ptgullas** [comment]
Adjusting the indent of an LI tag is also something I'd like to be able to do. The built-in Label control (when using TextType="Html") has an indent that's not large enough, but this one is too large for my liking. I might look into it when I have time.

**Comment by ptgullas** [comment]
Actually, it looks like an "AndroidListIndent" property was added (see #101 ). It works nicely.
