### ISSUE TITLE
How to set a font family to the label?

### ISSUE THREAD

**Issue by vhugogarcia** [matteobortolazzo/HtmlLabelPlugin#17]
Hello, I would like to load a local font I setup on my Xamarin.forms project. However, I could not find a way to do such thing.

Could you guide me, please?

Thanks in advance

**Comment by matteobortolazzo** [comment]
Hi, I never loaded a local font, on the standard label is already working?

**Comment by vhugogarcia** [comment]
yeah! If I set a default label in Xamarin forms I can see the properties for Font, FontFamily, FontSize and FontAttributes.

**Comment by matteobortolazzo** [comment]
So setting FontFamily in the HtmlLabel is not working? Both Android and iOS?

**Comment by vhugogarcia** [comment]
Actually, I made it work. I'm sorry @matteobortolazzo I got confuse and I was expected some kind of intellisense, however, I just applied the styles for the label and wit worked fantastic. 

One last question, for the links on the documentation you mention that "we don't forget to add http://" However, what if there is no a link and instead it is a "phone number" so it should be href="tel:XXX" or for email should be "emailto:XXX" would that work that as well?

**Comment by matteobortolazzo** [comment]
It should, not tested! Good point, thanks :) I'll update that section! Let me know please

**Comment by vhugogarcia** [comment]
I apologize for the delay @matteobortolazzo 

 I was able to test the tel: and mailto: and they worked very good as well, they launch the native app to execute such action.

Thanks in advance for this great plugin!

**Comment by matteobortolazzo** [comment]
Good :)
