### ISSUE TITLE
<ol> <ul> in android

### ISSUE THREAD

**Issue by gaffkins** [matteobortolazzo/HtmlLabelPlugin#19]
Hi, thank you for the library. 
On Android I got plain text when I use "< ol >" or "< ul >" tag.

**Comment by matteobortolazzo** [comment]
Hi, sorry but lists are not supported by the Android label so cannot do anything. Try using a webview instead.

**Comment by gaffkins** [comment]
It is true.
But I have a solution. I Added ListTagHandler
`public class ListTagHandler : Object, Html.ITagHandler 
    {
        bool first = true;

        public void HandleTag(bool opening, string tag, IEditable output, IXMLReader xmlReader)
        {
            if (tag.Equals("li"))
            {
                char lastChar = '0';
                if (output.Length() > 0)
                    lastChar = output.CharAt(output.Length() - 1);
                if (first)
                {
                    if (lastChar == '\n')
                        output.Append("\t•  ");
                    else
                        output.Append("\n\t•  ");
                    first = false;
                }
                else
                {
                    first = true;
                }
            }
        }
    }`

and in Your renderer change
` Html.FromHtml(value, FromHtmlOptions.ModeCompact,null, new ListTagHandler()) :
Html.FromHtml(value,null,  new ListTagHandler());`

It's render list but only unorder, for me it's ok :) Best

**Comment by matteobortolazzo** [comment]
Nice! Can you do a pull request? And can you make it work for ordered lists too? If you can't I'll try in the weekend. Thanks for the contribution :)

**Comment by gaffkins** [comment]
Yes I will pull request in the weekend. I will try to make ordered list.

**Comment by matteobortolazzo** [comment]
Thanks!! :)

**Comment by matteobortolazzo** [comment]
I'm testing and it's not working, at least on Android > N because HandleTag is called only when the parsed don't know the tag and from Android N it know <ul> and <li> so all the conditions are ignored

**Comment by gaffkins** [comment]
I will try to fix this.

**Comment by matteobortolazzo** [comment]
Done [2.2.0](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.2.0#)
I replaced every ul ol and li to ulc olc and lic so HandleTag  is called and everything works :)
