### ISSUE TITLE
In IOS, App crash after change NavigationPage

### ISSUE THREAD

**Issue by Xerosge** [matteobortolazzo/HtmlLabelPlugin#2]
Hi

I have a ContenPage with htmlLabelPlugin working in a Listview with labels, all work great but if after load this ContentPage try change to other page the app Crash

I create a blank page for test if the problem no the plugin but all work fine, only crash if I load the Page with the plugin and after try load any page of my project

Only crash in IOS, in android work fine

![error](https://user-images.githubusercontent.com/29948827/28017043-757009d2-6577-11e7-82ac-c3b8d19b7d63.png)

More info:

the pages loads in a NavigationPage

S2

**Comment by matteobortolazzo** [comment]
Can you provide me a simple example?

**Comment by Xerosge** [comment]
Hi, sure


https://mega.nz/#!a55w1ToC!yRgIPg5N9m9Iu4FMlS8MlXCYWcMUyyZGKXugRV4flDM

this is a sample, a menu with a listview with the plugin, 2 webview, a one detailpage, in ios you can open detail page and the two webpage (no open the url but don't mind), but if you open the listview and try open detail or webview the app cras

s2

**Comment by matteobortolazzo** [comment]
Very strange, however try with [1.0.4](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/1.0.4)

**Comment by Xerosge** [comment]
looks like it has been fixed, im testing and for now work well, great job

**Comment by matteobortolazzo** [comment]
Thanks I'll close the issue.
