### ISSUE TITLE
SetMaxLines and LineBreakMode.TailTruncation 

### ISSUE THREAD

**Issue by gaffkins** [matteobortolazzo/HtmlLabelPlugin#20]
When I use SetMaxLines and LineBreakMode.TailTruncation at the same time  :
on iOS - LineBreakMode.TailTruncation don't work, SetMaxLines work fine
on Android - SetMaxLines don't work, only one line is displaying, TailTruncation work.

**Comment by matteobortolazzo** [comment]
Hi, I'll investigate as soon as I can.

**Comment by matteobortolazzo** [comment]
Hi, both issues are caused by UILabel and TextView limitations. In theory iOS works if you set a constant width but I didn't test it yet.
