### ISSUE TITLE
iOS links problem with custom font

### ISSUE THREAD

**Issue by stepanic** [matteobortolazzo/HtmlLabelPlugin#22]
On Android everything works perfect with custom font, on iOS method `CharacterIndexForPoint` returns wrong index because I am using `NeoSans-Light` which is narrower than default system font `Helvetica`. And link works if the position of the link is close to the start of the string.

When I remove `FontFamily` from XAML, the character's index is calculated perfectly (with default Helvetica font family).

This issue is able to reproduce with a longer HTML string and links should be not on the start of the string where index position error is still in the link range and works, I have the link on index position 1057 and this method:
https://github.com/matteobortolazzo/HtmlLabelPlugin/blob/master/src/Plugin.HtmlLabel.iOS/HtmlLabelRenderer.cs#L173
Returns me that character index where I did click is 956, which does not make this condition true:

`if ((indexOfCharacter >= link.Range.Location) && (indexOfCharacter < link.Range.Location + link.Range.Length))` 

First, 49 characters location is returned correct, but when I click on the 50th index (51st character) it returns 49, but this depends on the character width and after hundreds of characters error becomes serious, and the browser will not be opened :(

**Comment by matteobortolazzo** [comment]
Hi, yes I understand the issue but I don't know how to solve it because CharacterIndexForPoint works only with the standard font I think... Any suggestion?

**Comment by stepanic** [comment]
I have made one interesting Hack :)

NeoSans-Light is narrower for 11% to 15% against iOS default system font and then giving scale and tolerance around the link is the hack how to click the index will work.

File: HtmlLabelRenderer.cs
```
...
var indexOfCharacter = (nint)layoutManager.CharacterIndexForPoint(locationOfTouchInTextContainer, textContainer, ref partialFraction);

// Problem is that method CharacterIndexForPoint always returns index based on UILabel font
// ".SFUIText" which is the default Helvetica iOS font
// HACK is to scale indexOfCharacter for 13% because NeoSans-Light is aproxamitely narrower font than ".SFUIText"
if (label.Font.Name == "NeoSans-Light") {
        indexOfCharacter = (nint)((double)indexOfCharacter * 1.13);
}
foreach (var link in linkList)
{
      var rangeLength = link.Range.Length;
      var tolerance = 0;
      if (label.Font.Name == "NeoSans-Light")
      {
           rangeLength = (nint)((double)rangeLength * 1.13);
           tolerance = 25;
      }
      // Xamarin version of NSLocationInRange?
      if ((indexOfCharacter >= (link.Range.Location - tolerance)) && (indexOfCharacter < (link.Range.Location + rangeLength + tolerance)))
      {
            return link.Url;
      }
}
return null;
...
```
Problem with this approach is that if links are close to each other then tolerance from one link can be over another link and position is not always translated correctly because this depends on which characters are before this link in the `UILabel`

The full solution is to choose one of the similar fonts available on the iOS
http://iosfonts.com/

`HelveticaNeue-Thin` is very similar to the `NeoSans-Light` and this is my final fix which will work in every case.

UILabel with any font from the website http://iosfonts.com/ will work perfectly.

**Comment by stepanic** [comment]
I also find one another problem with `HelveticaNeue` font family, I don't know why but when click index is approximately more than 2000 than indexOfCharacter is calculated around 2-3% and this is final fix

```
var indexOfCharacter = (nint)layoutManager.CharacterIndexForPoint(locationOfTouchInTextContainer, textContainer, ref partialFraction);

			nint scaledIndexOfCharacter = 0;
            // Problem is that method CharacterIndexForPoint always returns index based on UILabel font
            // ".SFUIText" which is the default Helvetica iOS font
            // HACK is to scale indexOfCharacter for 13% because NeoSans-Light is narrower font than ".SFUIText"
            if (label.Font.Name == "NeoSans-Light") {
                scaledIndexOfCharacter = (nint)((double)indexOfCharacter * 1.13);
            }

            // HelveticaNeue font family works perfect until character position in the string is more than 2000 chars
            // some uncosnsistent behaviour
            // if string has <b> tag than label.Font.Name from HelveticaNeue-Thin goes to HelveticaNeue-Bold
            if (label.Font.Name.StartsWith("HelveticaNeue", StringComparison.InvariantCulture)) {
                scaledIndexOfCharacter = (nint)((double)indexOfCharacter * 1.02);
            }

            foreach (var link in linkList)
            {
                var rangeLength = link.Range.Length;
                var tolerance = 0;
                if (label.Font.Name == "NeoSans-Light")
                {
                    rangeLength = (nint)((double)rangeLength * 1.13);
                    tolerance = 25;
                    indexOfCharacter = scaledIndexOfCharacter;
                }

                if (label.Font.Name.StartsWith("HelveticaNeue", StringComparison.InvariantCulture))
                {
                    if (link.Range.Location > 2000) {
                        indexOfCharacter = scaledIndexOfCharacter;
                    }
                }

                // Xamarin version of NSLocationInRange?
                if ((indexOfCharacter >= (link.Range.Location - tolerance)) && (indexOfCharacter < (link.Range.Location + rangeLength + tolerance)))
                {
                    return link.Url;
                }
            }
            return null;
```

I hope that this fix will save someone 2 days of life :D

**Comment by matteobortolazzo** [comment]
Great! :D I'm not able to test it because I don't have an iOS device here but can you do a pull request with the fix?

**Comment by matteobortolazzo** [comment]
@stepanic I'll add this in the coming release :) but I'm not able to test it so did you have other code to add?

**Comment by GreenRock** [comment]
Hi @matteobortolazzo  it does not work when using other fonts.
