### ISSUE TITLE
HtmlLabel not woring on android

### ISSUE THREAD

**Issue by babman92** [matteobortolazzo/HtmlLabelPlugin#23]
Hi @matteobortolazzo 
I use your plugin for display html on my app. Iimport package for 3 project, follow your guide but html code still display html code.
Please help me, thanks you.

My environment:
Windows 7, Visual Studio 2017(3), Xamarin Live

**Comment by matteobortolazzo** [comment]
Hi, can you provide me an example? The plugin work for other people so I don't know what to do

**Comment by babman92** [comment]
Please review this project,
I create project https://snag.gy/vwFgbO.jpg
And this is source: https://drive.google.com/open?id=1bGQ3LV616E9QwULOPVP7jJS2A9OSt8p3

Many thanks!

**Comment by babman92** [comment]
Hi @matteobortolazzo 
HtmlLabel not working at Xamarin Live but fine at Device, thanks you so much!

**Comment by matteobortolazzo** [comment]
Great! :)
