### ISSUE TITLE
HtmlAgilitypack dependency

### ISSUE THREAD

**Issue by PaulVrugt** [matteobortolazzo/HtmlLabelPlugin#25]
Hello,

It would be nice if the html agility pack is not a dependency for this plugin. Since it is only used in the UWP version of the plugin, and we are not developing for UWP, we don't want to have to include the agilitypack and all its dependencies to our project, when we don't need it

**Comment by PaulVrugt** [comment]
@matteobortolazzo 

yes you are correct. I've modified the source locally and removed all references to the agility pack, and removed the removehtmltags and ishtml property, so it builds again. However, I'd rather use the actual nuget package because now i have created a local fork in our apps

**Comment by matteobortolazzo** [comment]
In the next release I will remove the dependency :)

**Comment by PaulVrugt** [comment]
Nice! Looking forward to it

**Comment by matteobortolazzo** [comment]
[Pre release of v3](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/3.0.0-beta1)
