### ISSUE TITLE
Force font to be the default one

### ISSUE THREAD

**Issue by TGlev** [matteobortolazzo/HtmlLabelPlugin#26]
Hello,

I'm using this plugin inside of my app, but there is something that bothers me. The font of the HtmlLabel is different from the font used by the phones.

I've tried setting the FontFamily of the label to "San-Francisco" but this didn't do anything.

**Comment by matteobortolazzo** [comment]
Very strange, this was fixed https://github.com/matteobortolazzo/HtmlLabelPlugin/pull/15

**Comment by TGlev** [comment]
`Label.FontFamily = "San-Francisco";`

This is what I use to the fontfamily of your label, Label is a reference to the HTMLLabel I have.
I am on version 2.2.0

**Comment by TGlev** [comment]
Turns out, this was different from what we thought.

The problem was that I was comparing the text of the htmllabel with the text of a different label. The different label had the bold fontattribute, while the HTMLlabel didn't have that. 

Apparently, there are differences in fonts with bold and non bold letters.

**Comment by TGlev** [comment]
As soon as I make the HTMLLabel bold by using
`Label.FontAttributes = FontAttributes.Bold;`

it works. The font of the label changes.
Same goes for making it italic.

But as soon as I remove this line of code, or give it FontAttributes.None, the font doesnt change anymore.

**Comment by TGlev** [comment]
So what it looks like now is that the fontfamily stops working as soon as you change the content of the label.

I need to update the content of my label from time to time. The first time I put content in it, it works. The second time it does not. The third time is does not and so on. The FontFamily property is still set though.

**Comment by TGlev** [comment]
I managed to create a workaround by doing this:
`Label.FontFamily = "";
Label.FontFamily = "San-Francisco";`

Every time I update the content of my label.

**Comment by matteobortolazzo** [comment]
Ok thanks I'll check this out as soon as I can

**Comment by matteobortolazzo** [comment]
Both iOS and Android?

**Comment by matteobortolazzo** [comment]
It makes no sense because everytime you update the label text the HTML+CSS (font-family: something;) is generated from scratch
