### ISSUE TITLE
Html links in webview

### ISSUE THREAD

**Issue by CR4567** [matteobortolazzo/HtmlLabelPlugin#27]
Hi,

do you think it's possible to create an option that html links are opened in an internal web view, instead of the device browser?

Best regards,
Chris

**Comment by matteobortolazzo** [comment]
I don't know, I think it's possible but I need time

**Comment by matteobortolazzo** [comment]
I'll check today :) sorry the late

**Comment by matteobortolazzo** [comment]
Navigating and Navigated events will be added :D so @CR4567 handle those events an you'll be fine

**Comment by CR4567** [comment]
sounds great, thanks for your work!

**Comment by tbaggett** [comment]
Awesome, thank you! And no need to ever apologize for not getting your free open source project updated sooner. Thanks for adding the events.

**Comment by matteobortolazzo** [comment]
[Pre release of v3](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/3.0.0-beta1)
