### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mwallon** [matteobortolazzo/HtmlLabelPlugin#28]
Hi, when I try to install this plugin I get this error "Could not install package 'Xam.Plugin.HtmlLabel 2.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Do you know what I'm doing wrong?
/magnus

**Comment by matteobortolazzo** [comment]
What version of xamarin are you using?

**Comment by chkrishna2001** [comment]
I am also having same issue, i am using xamarin.forms 3.1.0.583944

**Comment by matteobortolazzo** [comment]
Hi .NET Standard 1.3 only supports .NET 4.6+ so you need to convert your PCL in order to install it. [DOCS](https://github.com/dotnet/standard/blob/master/docs/versions.md)
