### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by TGlev** [matteobortolazzo/HtmlLabelPlugin#30]
Hi there,
Im now working on the android side of my project and I have come to the conclusion that the plugin is not functioning on Android.

I have tested it on an actual device, Samsung Galaxy S5 running Android 6.0. Tried in Debug and Release.
The label is there, but the HTML tags are still in the text and links are not functioning.

I am on the latest version, I did add the initialization line to my MainActivity.

**Comment by matteobortolazzo** [comment]
Mmm you're the only one, can you provide me a sample project?

**Comment by TGlev** [comment]
@matteobortolazzo Have you found something already?

**Comment by matteobortolazzo** [comment]
Hi, I'm very sorry.. I'm crazy busy at work this month.. Tomorrow I'll check your project

**Comment by TGlev** [comment]
Okay thank you :)

**Comment by matteobortolazzo** [comment]
I need MediaManager 0.5.0, can I use 0.4?

**Comment by matteobortolazzo** [comment]
Sorry, It's 40 min that I try to open your solution, I've tried everything but it freezes Visual Studio everytime and I have an i7 :(

**Comment by TGlev** [comment]
Too bad. I always open the solution in visual studio for mac.
Can you browse through the source code and see if there is something wrong there?

**Comment by TGlev** [comment]
Could it be something with Linker? Android manifest? Should I build in release?

**Comment by TGlev** [comment]
I tried it in the emulator, same issue.

**Comment by TGlev** [comment]
Found a workaround, sortof.
`HtmlLabel.SetIsHtml(ContentLabel, false);
            HtmlLabel.SetIsHtml(ContentLabel, true);`

There are two issues though:
1. The images are not being displayed.
2. Links are not being highlighted blue and are not working either

**Comment by TGlev** [comment]
I imported your code and its still not working. Got the same issues, altough the above mentioned workaround also stopped working now.

**Comment by TGlev** [comment]
Imported your code, still got the same issues.

**Comment by TGlev** [comment]
Links are working now though.

**Comment by TGlev** [comment]
Images are being displayed as small blue squares...

**Comment by matteobortolazzo** [comment]
Images won't be display because it's a label not a webview, It's not my plugin is Android. 
Links will be handled in an entirely new way in the next release so maybe it will work

**Comment by TGlev** [comment]
Images are working on iOS. Is that a platform difference?

**Comment by matteobortolazzo** [comment]
Yes, Android TextView does not support images

**Comment by matteobortolazzo** [comment]
If I send you the next version (v3.0.0), could you test it on your app?

**Comment by TGlev** [comment]
Yes I can test it.
What is new in it?

**Comment by matteobortolazzo** [comment]
So, removed IsHtml and RemoveHtmlTags properties because they were useless and HtmlAgilityPack is also removed because of this. Navigated and Navigating events when users tap on links and Xamarin.Forms 3.0. Now I'll setup a CI/CD pipeline on VSTS than I'll publish I preview version of the release so you'll be able to test it :) thanks!

**Comment by matteobortolazzo** [comment]
[Here](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/3.0.0-beta1)

**Comment by TGlev** [comment]
Sorry, Im too busy to test.
