### ISSUE TITLE
Unwanted newline character at end of text

### ISSUE THREAD

**Issue by seongjaey** [matteobortolazzo/HtmlLabelPlugin#31]
Hello.
Thank you for your project.

My proble is character '\n' is added at end of text.
For example, "\<b\>Welcome\</b\>" is converted to "Welcome\n".

I made a custom renderer to remove last '\n' character in Control.Text. 
However, after applying this renderer, all html attributes are removed.

I think this is caused by HtmlLabelHelper. Because it wraps whole text with \<div\> tag.
When I make a text like "\</div\>\<span\>\<b\>Welcome\</b\>\</span\>\<div\>",
character 'n' is added to begin and end of the text.

I'm using the version below.

Xamarin Forms : 2.5.0.280555
HtmlLabel : 2.2.0

Thanks!

**Comment by matteobortolazzo** [comment]
Hi, I'll check it as soon as I can

**Comment by matteobortolazzo** [comment]
Sorry for the late, can you send me an example? I don't new lines

**Comment by matteobortolazzo** [comment]
The second is a normal Label so I don't think it's my fault
![screenshot_2018-06-10-17-54-47](https://user-images.githubusercontent.com/15217470/41203468-826d4d76-6cd7-11e8-9aa4-4c6e658cc0ad.png)

**Comment by matteobortolazzo** [comment]
Great :)

**Comment by matteobortolazzo** [comment]
Great :)
