### ISSUE TITLE
Build Error The type 'htmlLabel:HtmlLabel' was not found.

### ISSUE THREAD

**Issue by primehalo** [matteobortolazzo/HtmlLabelPlugin#33]
I used NuGet to install the latest version and followed all the instructions but was getting build errors. After looking at the example in the source I was able to get it working by changing this:
`xmlns:htmlLabel="clr-namespace:Plugin.HtmlLabel;assembly=Plugin.HtmlLabel"`
to this:
`xmlns:htmlLabel="clr-namespace:LabelHtml.Forms.Plugin.Abstractions;assembly=HtmlLabel.Forms.Plugin"`

**Comment by matteobortolazzo** [comment]
Oh thanks, I changed the namespace but not the README. Done
