### ISSUE TITLE
UL null reference error in listdictionary internal, only on Android

### ISSUE THREAD

**Issue by Eldin66** [matteobortolazzo/HtmlLabelPlugin#39]
This piece of HTML provides a null reference error in listdictionaryinternal only on Android, on iOS everything works fine. 

`<ul style="list-style-type&#58;disc;"><li>Het project moet leiden naar een op zijn minst gelijkwaardige omgeving in de Microsoft Cloud,&#160; </li><li>De nieuwe omgeving moet toekomstbestendig zijn en geen gebruik maken van maatwerk,&#160; </li><li>Het moet samenwerken faciliteren, </li><li>De omgeving moet gebruikersvriendelijk zijn voor alle betrokkenen</li><li>Hoge mate van beschikbaarheid bieden en het ontzorgen van IT Beheer.</li></ul>`

**Comment by Eldin66** [comment]
Apparently `style="list-style-type&#58;disc;"` caused this issue. I removed it and the error went away.

**Comment by matteobortolazzo** [comment]
Good :)
