### ISSUE TITLE
Stop the navigation

### ISSUE THREAD

**Issue by hjavaher** [matteobortolazzo/HtmlLabelPlugin#40]
Hi,
I'm hooking into the Navigating event to see if the link in the HtmlLabel is a hashtag.  What I'm wondering is how do I cancel the navigation after I've processed the hashtag so that the app doesn't follow through and open safari?

Thanks,
Jason

**Comment by matteobortolazzo** [comment]
Hi, try with e.Cancel = true

**Comment by hjavaher** [comment]
Man that was so obvious. I'm kinda ashamed of asking it :) I do have another issue but I'll open a new issue for it.
Thank you for the support and great plugin
