### ISSUE TITLE
Support for HashTag as a link

### ISSUE THREAD

**Issue by hjavaher** [matteobortolazzo/HtmlLabelPlugin#41]
Hi,
I have the following string in the HtmlLabel:
 
htmlLabel.Text = "`<a href='#awesome'>#awesome</a>`"

I have confirmed that if I put a regular fully qualified URL, it's clickable and it navigates to that link but when I put a hashtag it does not. The workaround I've come up with so far is to put a bogus fully qualified URL that has the hashtag in the href and then filter it out in the Navigating event. It would be awesome to have support for hash tags and mentions (@) out of the box though. 

Maybe there is and I just missed it?

Thanks

**Comment by hjavaher** [comment]
Also, I just discovered that the following link is also not clickable. Can anyone point me to a possible workaround?

https://link.com/hash/швордвт 

as soon as put in unicode characters it does not work

**Comment by matteobortolazzo** [comment]
Hi, why do you need 'hashtag' href? Where do they go? For page navigation, you need to use the WebView.
And for unicode chars, I sincerely don't know how to fix it.

**Comment by hjavaher** [comment]
Hi,
I'm using your plugin to handle hashtag clicks in my app. So when a user taps on a hashtag, the app intercepts and cancels the request but handles the tap (as in open the controller)

everything works fine now except if the link is in another language. I'm debugging it right now and if I see why, I'll create a pull request (if I can fix it)

**Comment by matteobortolazzo** [comment]
I'll close this since hashtags works
