### ISSUE TITLE
Cannot add HtmlLabel from C#

### ISSUE THREAD

**Issue by alexmanie** [matteobortolazzo/HtmlLabelPlugin#42]
When I try to add a new HtmlLabel from C# my whole page comes blank (white).
This is a code snippet of what I'm doing:

`var htmlLabel = new HtmlLabel();`
`  htmlLabel.Text = "<b>hello</b>";   `           
 ` myLayout.Children.Add(htmlLabel);`

And this is the XAML code where the new HtmlLabel will be created:

`<ContentView.Content>`
`        <StackLayout x:Name="ContentLayout">`
`            <!-- filled in code behind -->`
`        </StackLayout>  `
`    </ContentView.Content>`

The whole screen becomes white, and nothing is displayed.
I can't see any error on the output window and I'm not getting any Exception at runtime.

Any ideas?

**Comment by matteobortolazzo** [comment]
Hi, sorry the late answer.
I never tried to add the label in the code but I have no idea why is not working, It's a native label with some options. I'll try to find the error as soon as I can

**Comment by alexmanie** [comment]
hi @matteobortolazzo ,
giving you more details about the error.

the binding between the view and the HtmlLabel source is done through a Dependency object, where the app binds an html text and then, that html text is set to a new HtmlLabel on the code behind of my custom control.

`
[XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class ExtendedHtmlLabeledBody : ContentView
    {
        public ExtendedHtmlLabeledBody()
        {
            InitializeComponent();
        }

        public string Text { get; set; }

        public static readonly BindableProperty TextProperty = BindableProperty.Create(
                                                         propertyName: "Text",
                                                         returnType: typeof(string),
                                                         declaringType: typeof(ExtendedHtmlLabeledBody),
                                                         defaultValue: "",
                                                         defaultBindingMode: BindingMode.TwoWay,
                                                         propertyChanged: TextPropertyChanged);

        private static void TextPropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var control = (ExtendedHtmlLabeledBody)bindable;
            string bodyText = newValue?.ToString();

            if (bodyText != null)
                SetContent(bodyText);
        }

        private static void SetContent(string bodyText)
        {
            try
            {
                var htmlLabel = new HtmlLabel();
                htmlLabel.Text = bodyText;
                ContentStatic.Children.Add(htmlLabel);
            }
            catch (Exception ex)
            {

            }
        }
    }
`

Hope it helps you to reproduce the scenario.
Thanks in advance.

**Comment by alexmanie** [comment]
Problem solved!
Just need to change the order of the text assignment and Childre.Add instruction.

That code works:
`var htmlLabel = new HtmlLabel();
            ContentStatic.Children.Add(htmlLabel);
            htmlLabel.Text = bodyText;
`

Apologize.

**Comment by matteobortolazzo** [comment]
Oh good :) but I'll check if I can make it work without this work around
