### ISSUE TITLE
Plugin references in UWP

### ISSUE THREAD

**Issue by zwithus** [matteobortolazzo/HtmlLabelPlugin#43]
It seems that the namespaces has been updated in Plugin ver 3.0.1 and it's not possible to setup and use the plugin in App.xaml.cs for UWP environment (Android and iOS work fine). The htmlLabel just shows the content as plain text including HTMl tags instead of data in html format.

**Comment by BtrJay** [comment]
I have exactly same issue. Please do fix

**Comment by matteobortolazzo** [comment]
Hi, I'll check tomorrow

**Comment by zwithus** [comment]
Thanks for your reply! Do you know when it will approximately be fixed? I am thinking about releasing the UWP version of my app

**Comment by matteobortolazzo** [comment]
I hope by the end of the week.

**Comment by matteobortolazzo** [comment]
Are you targeting something less than 17134?

**Comment by zwithus** [comment]
We are targeting the minimum Windows 10 build that supports .NET Standard 2.0 (aka Fall Creators Update, build 16299). Is that a problem to be less than 17134?

**Comment by matteobortolazzo** [comment]
Now it only works with 17134 or greater. I need to check why is not compiling with 16299

**Comment by zwithus** [comment]
I have updated the plugin to 3.0.1.7-Beta and changed the min version of UWP project to 17134, but still cannot make it working. What is the proper way of initializing the HtmlLabel in the App.xaml.cs of UWP project? You have different implementations in your documentation and the sample project.

In the sample/test project:
`LabelHtml.Forms.Plugin.UWP.HtmlLabelRenderer.Initialize();`

In the documentation:
```
var rendererAssemblies = new[] { typeof(HtmlLabelRenderer).GetTypeInfo().Assembly };
Xamarin.Forms.Forms.Init(e, rendererAssemblies);
HtmlLabelRenderer.Initialize();
```
None of above works for me.

**Comment by matteobortolazzo** [comment]
Try with 16299 and plugin 3.0.2.1. On a new project it works

**Comment by zwithus** [comment]
Thanks for your support, but still does not work properly. See image below that are screenshots from UWP and iOS projects for the same HTML content. Is the content valid for the UWP?

![sv_lexikon_uwp](https://user-images.githubusercontent.com/14153324/48982629-6657b080-f0e5-11e8-8278-02bad023454d.jpg)
![sv_lexikon_ios](https://user-images.githubusercontent.com/14153324/48982630-6657b080-f0e5-11e8-9525-bdae56232486.jpg)

Is there any way that I can investigate more at my side?

**Comment by matteobortolazzo** [comment]
In the readme there's the list of tags supported in UWP. <html> and <body> are not on the list.

**Comment by zwithus** [comment]
I have not managed to test this. I need to work a little bit on my project to change the HTML content so it considers UWP capabilities. I'll update you as soon as I check it.

**Comment by matteobortolazzo** [comment]
I'll close this for now
