### ISSUE TITLE
Crash in iOS

### ISSUE THREAD

**Issue by bill2004158** [matteobortolazzo/HtmlLabelPlugin#44]
the stacktrace:

 > 2018-11-14 18:24:58.976551+0100 Mobile.iOS[2280:27643] Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.84.15/UITableView.m:2055
 > objc[2280]: Invalid or prematurely-freed autorelease pool 0x7fc5a67e1b70.
 > 2018-11-14 18:24:59.075851+0100 Mobile.iOS[2280:27643] critical: Stacktrace:
 > 2018-11-14 18:24:59.076071+0100 Mobile.iOS[2280:27643] critical:   at <unknown >  <0xffffffff > 
 > 2018-11-14 18:24:59.076243+0100 Mobile.iOS[2280:27643] critical:   at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objc_msgSend_IntPtr_IntPtr_ref_IntPtr_ref_IntPtr (intptr,intptr,intptr,intptr,intptr&,intptr&) [0x00010] in <6a026a6503ca4935b5bb3ed241d053fe > :0
 > 2018-11-14 18:24:59.076395+0100 Mobile.iOS[2280:27643] critical:   at Foundation.NSAttributedString..ctor (Foundation.NSData,Foundation.NSDictionary,Foundation.NSDictionary&,Foundation.NSError&) [0x0002d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSAttributedString.g.cs:129
 > 2018-11-14 18:24:59.076545+0100 Mobile.iOS[2280:27643] critical:   at Foundation.NSAttributedString..ctor (Foundation.NSData,Foundation.NSAttributedStringDocumentAttributes,Foundation.NSDictionary&,Foundation.NSError&) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSAttributedString.g.cs:141
 > 2018-11-14 18:24:59.076718+0100 Mobile.iOS[2280:27643] critical:   at Foundation.NSAttributedString..ctor (Foundation.NSData,Foundation.NSAttributedStringDocumentAttributes,Foundation.NSError&) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSAttributedString.iOS.cs:47
 > 2018-11-14 18:24:59.076875+0100 Mobile.iOS[2280:27643] critical:   at LabelHtml.Forms.Plugin.iOS.HtmlLabelRenderer.CreateAttributedString (UIKit.UILabel,string) [0x0007d] in <5c9470be6fc9415cbba0781ca81522c4 > :0
 > 2018-11-14 18:24:59.077070+0100 Mobile.iOS[2280:27643] critical:   at LabelHtml.Forms.Plugin.iOS.HtmlLabelRenderer.UpdateText () [0x00056] in <5c9470be6fc9415cbba0781ca81522c4 > :0
 > 2018-11-14 18:24:59.077415+0100 Mobile.iOS[2280:27643] critical:   at LabelHtml.Forms.Plugin.iOS.HtmlLabelRenderer.OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1<Xamarin.Forms.Label > ) [0x00019] in <5c9470be6fc9415cbba0781ca81522c4 > :0
 > 2018-11-14 18:24:59.077940+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .SetElement (TElement_REF) [0x00122] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:259
 > 2018-11-14 18:24:59.078131+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:141
 > 2018-11-14 18:24:59.078384+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement) [0x00014] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:198
 > 2018-11-14 18:24:59.078815+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement) [0x0003d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:97
 > 2018-11-14 18:24:59.079033+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:46
 > 2018-11-14 18:24:59.079315+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .SetElement (TElement_REF) [0x000de] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:246
 > 2018-11-14 18:24:59.079718+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:141
 > 2018-11-14 18:24:59.080040+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement) [0x00014] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:198
 > 2018-11-14 18:24:59.080182+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement) [0x0003d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:97
 > 2018-11-14 18:24:59.080403+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:46
 > 2018-11-14 18:24:59.080738+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .SetElement (TElement_REF) [0x000de] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:246
 > 2018-11-14 18:24:59.080978+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:141
 > 2018-11-14 18:24:59.081289+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement) [0x00014] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:198
 > 2018-11-14 18:24:59.081456+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement) [0x0003d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:97
 > 2018-11-14 18:24:59.081757+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:46
 > 2018-11-14 18:24:59.082021+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .SetElement (TElement_REF) [0x000de] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:246
 > 2018-11-14 18:24:59.082326+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:141
 > 2018-11-14 18:24:59.082539+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement) [0x00014] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:198
 > 2018-11-14 18:24:59.082906+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement) [0x0003d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:97
 > 2018-11-14 18:24:59.083375+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:46
 > 2018-11-14 18:24:59.083693+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .SetElement (TElement_REF) [0x000de] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:246
 > 2018-11-14 18:24:59.083890+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1<TElement_REF > .Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:141
 > 2018-11-14 18:24:59.084106+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement) [0x00014] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:198
 > 2018-11-14 18:24:59.084405+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.ListViewRenderer/UnevenListViewDataSource.CalculateHeightForCell (UIKit.UITableView,Xamarin.Forms.Cell) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ListViewRenderer.cs:792
 > 2018-11-14 18:24:59.084591+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.ListViewRenderer/UnevenListViewDataSource.GetEstimatedRowHeight (UIKit.UITableView) [0x0008c] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ListViewRenderer.cs:732
 > 2018-11-14 18:24:59.084879+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.ListViewRenderer.UpdateEstimatedRowHeight () [0x0005f] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ListViewRenderer.cs:417
 > 2018-11-14 18:24:59.085154+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.ListViewRenderer.UpdateItems (System.Collections.Specialized.NotifyCollectionChangedEventArgs,int,bool) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ListViewRenderer.cs:547
 > 2018-11-14 18:24:59.085441+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Platform.iOS.ListViewRenderer.OnCollectionChanged (object,System.Collections.Specialized.NotifyCollectionChangedEventArgs) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ListViewRenderer.cs:316
 > 2018-11-14 18:24:59.086408+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Internals.TemplatedItemsList`2<TView_REF, TItem_REF > .OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs) [0x0000a] in D:\a\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:771
 > 2018-11-14 18:24:59.086680+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.Internals.TemplatedItemsList`2<TView_REF, TItem_REF > .OnProxyCollectionChanged (object,System.Collections.Specialized.NotifyCollectionChangedEventArgs) [0x0045f] in D:\a\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:1097
 > 2018-11-14 18:24:59.086924+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.ListProxy.OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs) [0x0000a] in D:\a\1\s\Xamarin.Forms.Core\ListProxy.cs:233
 > 2018-11-14 18:24:59.087383+0100 Mobile.iOS[2280:27643] critical:   at Xamarin.Forms.ListProxy/< > c__DisplayClass33_0.<OnCollectionChanged > b__0 () [0x00018] in D:\a\1\s\Xamarin.Forms.Core\ListProxy.cs:206
 > 2018-11-14 18:24:59.087920+0100 Mobile.iOS[2280:27643] critical:   at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSAction.cs:152
 > 2018-11-14 18:24:59.088260+0100 Mobile.iOS[2280:27643] critical:   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00020] in <7d5a05cfcb09432d8cc656b9d781e54b > :0
 > 2018-11-14 18:24:59.088451+0100 Mobile.iOS[2280:27643] critical:   at <unknown >  <0xffffffff > 
 > 2018-11-14 18:24:59.088773+0100 Mobile.iOS[2280:27643] critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) [0x0005c] in <6a026a6503ca4935b5bb3ed241d053fe > :0
 > 2018-11-14 18:24:59.089113+0100 Mobile.iOS[2280:27643] critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:79
 > 2018-11-14 18:24:59.089341+0100 Mobile.iOS[2280:27643] critical:   at UIKit.UIApplication.Main (string[],string,string) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:63
 > 2018-11-14 18:24:59.089591+0100 Mobile.iOS[2280:27643] critical:   at Mobile.iOS.Application.Main (string[]) [0x00002] in G:\ms\Projects\msmobile\Mobile\Mobile.iOS\Main.cs:20
 > 2018-11-14 18:24:59.090058+0100 Mobile.iOS[2280:27643] critical:   at (wrapper runtime-invoke) <Module > .runtime_invoke_void_object (object,intptr,intptr,intptr) [0x00051] in <9e014d41a59e4122acfb41ac306a63d6 > :0
 > 2018-11-14 18:24:59.090337+0100 Mobile.iOS[2280:27643] critical: 
 > Native stacktrace:
 > 2018-11-14 18:24:59.110288+0100 Mobile.iOS[2280:27643] critical: 	0   Mobile.iOS                0x000000010d759be4 mono_handle_native_crash + 244
 > 2018-11-14 18:24:59.110663+0100 Mobile.iOS[2280:27643] critical: 	1   libsystem_platform.dylib            0x000000011d6b0f5a _sigtramp + 26
 > 2018-11-14 18:24:59.110906+0100 Mobile.iOS[2280:27643] critical: 	2   ???                                 0x00007ffee270f7e0 0x0 + 140732697475040
 > 2018-11-14 18:24:59.111091+0100 Mobile.iOS[2280:27643] critical: 	3   libsystem_kernel.dylib              0x000000011d68525f abort_with_payload_wrapper_internal + 0
 > 2018-11-14 18:24:59.111297+0100 Mobile.iOS[2280:27643] critical: 	4   libobjc.A.dylib                     0x000000011beff1f5 _ZL12_objc_fatalvyyPKcP13__va_list_tag + 108
 > 2018-11-14 18:24:59.111503+0100 Mobile.iOS[2280:27643] critical: 	5   libobjc.A.dylib                     0x000000011beff11e __objc_error + 0
 > 2018-11-14 18:24:59.111775+0100 Mobile.iOS[2280:27643] critical: 	6   libobjc.A.dylib                     0x000000011bf125b0 _objc_autoreleasePoolPush + 0
 > 2018-11-14 18:24:59.112046+0100 Mobile.iOS[2280:27643] critical: 	7   CoreFoundation                      0x000000011b007356 _CFAutoreleasePoolPop + 22
 > 2018-11-14 18:24:59.112637+0100 Mobile.iOS[2280:27643] critical: 	8   UIKitCore                           0x00000001256e80a3 _prepareForCAFlush + 143
 > 2018-11-14 18:24:59.113079+0100 Mobile.iOS[2280:27643] critical: 	9   UIKitCore                           0x000000012571777f _beforeCACommitHandler + 15
 > 2018-11-14 18:24:59.113294+0100 Mobile.iOS[2280:27643] critical: 	10  CoreFoundation                      0x000000011af4b037 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
 > 2018-11-14 18:24:59.113842+0100 Mobile.iOS[2280:27643] critical: 	11  CoreFoundation                      0x000000011af454ce __CFRunLoopDoObservers + 430
 > 2018-11-14 18:24:59.114192+0100 Mobile.iOS[2280:27643] critical: 	12  CoreFoundation                      0x000000011af45244 CFRunLoopRunSpecific + 660
 > 2018-11-14 18:24:59.114812+0100 Mobile.iOS[2280:27643] critical: 	13  UIFoundation                        0x00000001218c4bf2 -[NSHTMLReader _loadUsingWebKit] + 1918
 > 2018-11-14 18:24:59.115241+0100 Mobile.iOS[2280:27643] critical: 	14  UIFoundation                        0x00000001218c5fc7 -[NSHTMLReader attributedString] + 22
 > 2018-11-14 18:24:59.115642+0100 Mobile.iOS[2280:27643] critical: 	15  UIFoundation                        0x000000012185171e _NSReadAttributedStringFromURLOrData + 5452
 > 2018-11-14 18:24:59.115971+0100 Mobile.iOS[2280:27643] critical: 	16  UIFoundation                        0x000000012185013e -[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 117
 > 2018-11-14 18:24:59.116521+0100 Mobile.iOS[2280:27643] critical: 	17  Mobile.iOS                0x000000010d989bd9 xamarin_dyn_objc_msgSend + 217
 > 2018-11-14 18:24:59.117385+0100 Mobile.iOS[2280:27643] critical: 	18  ???                                 0x00000001440585bb 0x0 + 5436179899
 > 2018-11-14 18:24:59.117955+0100 Mobile.iOS[2280:27643] critical: 
 > - - - - - - -
 > Got a SIGABRT while executing native code. This usually indicates
 > a fatal error in the mono runtime or one of the native libraries 
 > used by your application.
 >   - - - - - - -
 > The app has been terminated.
 >

**Comment by matteobortolazzo** [comment]
Please provide a code example.
