### ISSUE TITLE
Only second link is underlined inside a string with 2 a-tags

### ISSUE THREAD

**Issue by sdebruyn** [matteobortolazzo/HtmlLabelPlugin#48]
In the following string on Android:

```
This is an example. Call <a href="003221234567">+32 2 123 45 67</a> or call <a href="003221234568">+32 2 123 45 68</a>.
```

Only the second link is underlined.

**Comment by matteobortolazzo** [comment]
Hi,
sorry for the 1+ year delay.
I was not supporting the plugin anymore.
Now I plan to release a new version.
Did you find a solution?
If not will investigate this.
Thanks

**Comment by matteobortolazzo** [comment]
Hi, I am testing now and both links are underlined.
However it will not work if you don't add "tel://".
I am closing this one.
