### ISSUE TITLE
HTML Table Support

### ISSUE THREAD

**Issue by Jhanbury** [matteobortolazzo/HtmlLabelPlugin#5]
Currently, the control just displays the text inside of a Table when given a standard HTML table.
Could the control support tables fully and be able to render the border etc?

### **Example**

**Expected HTML:**
<table><tbody><tr style="height:50%;"><td style="width:25%;">test&nbsp;</td><td style="width:25%;">&nbsp;</td><td style="width:25%;">&nbsp;</td><td style="width:25%;">&nbsp;</td></tr><tr style="height:50%;"><td style="width:25%;">&nbsp;</td><td style="width:25%;">&nbsp;</td><td style="width:25%;">&nbsp;test</td><td style="width:25%;">&nbsp;</td></tr></tbody></table>

**Result:**

test   test

@matteobortolazzo any idea on whether this is possible?

**Comment by matteobortolazzo** [comment]
Hi, sorry for the late answer.
Try to use inline CSS to display borders/colors or the border attribute on the table

**Comment by Jhanbury** [comment]
@matteobortolazzo  Inline CSS does not solve the issue here is the test data I used:
```
<table border="1px solid #dddddd;">
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
</table>
```

Once again the table appears with no border
Do you have any examples of tables working?

**Comment by matteobortolazzo** [comment]
You're right, Android doesn't support the table tag. And I makes sense.. Why do you need a table into a label when there's the WebView?

**Comment by Jhanbury** [comment]
I was trying out the label as an alternative for WebView for a preview, as I needed to handle a click event which would take me to a full page editor. 

using the HTML label made it easier to handle the click event and also had better layout options than the WebView (labels doesn't require a specific height)

But if it's not supported there's not a lot we can do :) 

Thanks  @matteobortolazzo for the help on this

**Comment by matteobortolazzo** [comment]
That's a problem if you have the data into a DB you could use a GridLayout with labels or labels with calculated absolute positions

**Comment by matteobortolazzo** [comment]
Or you can use [this](https://www.devexpress.com/Products/Xamarin/)

**Comment by Jhanbury** [comment]
I'm currently using Grid layout and the problem is the WebView is not able to adapt to the size of the content.  I'll have another look at what the options are. Labels were nice as I could set max lines with a line custom work so that it would expand to a point. 

Thanks for the links

**Comment by matteobortolazzo** [comment]
You can do something live this with the GridLayout:

~~~~
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>

    <Label Grid.Row="0" Grid.Column="0" Text="Company" />
    <Label Grid.Row="0" Grid.Column="1" Text="Contact" />
    <Label Grid.Row="0" Grid.Column="3" Text="Country" />

    <Label Grid.Row="1" Grid.Column="0" Text="Alfreds Futterkiste" />
    <Label Grid.Row="1" Grid.Column="1" Text="Maria Anders" />
    <Label Grid.Row="1" Grid.Column="3" Text="Germany" />

    <Label Grid.Row="2" Grid.Column="0" Text="Centro comercial Moctezuma" />
    <Label Grid.Row="2" Grid.Column="1" Text="Francisco Chang" />
    <Label Grid.Row="2" Grid.Column="3" Text="Mexico" />
</Grid>
~~~~

**Comment by Jhanbury** [comment]
Ah sorry, @matteobortolazzo may have misled you with the test data I used.
The source of the label is dynamic so it may or may not have a table, it could be any type of formatted text.
My only requirement is that it supports tables if they appear.

**Comment by matteobortolazzo** [comment]
Ok now it's clear, you need a custom WebView, it's the only things that could work I think...
Try [this code](https://forums.xamarin.com/discussion/25967/setting-height-of-webview-dynamically) and for the click, if it's not working directly you can add a transparent Frame o something like that over the custom WebView, both into a Grid

**Comment by Jhanbury** [comment]
@matteobortolazzo I was thinking of disabling the Webview and then using the transparent Frame to handle the click event. Strangely enough, the table is not being displayed here either by the Android WebView. A quick solution would be to create a local HTML page with a CDN link to bootstrap and let that handle the styling of the table in the web view. I don't love that method however it's a temporary fix.
