### ISSUE TITLE
ul and ol adding newline at the beginning on android

### ISSUE THREAD

**Issue by AlexSchuetz** [matteobortolazzo/HtmlLabelPlugin#50]
I recognized, that ul and ol at the start of a text will produce a newline on android. But the newline character should only be added, if there is text before the list (like it is done on IOS).

Also linebreaks don't get intended.

Probably "LeadingMarginSpan" should be used inside the TagHandler.

**Comment by matteobortolazzo** [comment]
Closed by #53
