### ISSUE TITLE
font size doesn't work on android

### ISSUE THREAD

**Issue by FRIDIE** [matteobortolazzo/HtmlLabelPlugin#51]
`HomeLabel.Text = "<span style='font-size: 45px'><strong>Hello</strong> world!</span>";`

It works on iOS but it doesn't work on android

**Comment by alexthekid07** [comment]
I use "pt" instead of "px" and it works on Android

**Comment by matteobortolazzo** [comment]
Hi, it's an Android limitation. Also, you can try to use the <font> tag.
