### ISSUE TITLE
Navigating not called on iOS

### ISSUE THREAD

**Issue by donmesserli** [matteobortolazzo/HtmlLabelPlugin#54]
I am displaying an image with an HTML string under it. It displays fine and the method I put in Navigating gets called on Android. Navigating never gets called on iOS. I am not using a custom font.

**Comment by matteobortolazzo** [comment]
Hi, sorry the late answer.
So, navigation in iOS is not native, what happens is that based on the font and the text, it calculates if you are clicking on a link or not. Images, link custom fonts, breaks the calculation.
So until Apple provides a native way to detect links, it's not possible.
What you can do is put 2 labels, one with the image and one without.
