### ISSUE TITLE
show extra bullet on empty ul element

### ISSUE THREAD

**Issue by blackjuna** [matteobortolazzo/HtmlLabelPlugin#56]

**Comment by blackjuna** [comment]
hi.
i hve <html:HtmlLabel Text="{Binding ApprovalNotes}"/>

and the value of the approval notes is
<b> You are approving this request for </b><ul><li>Direct supervisor of Dhea Kurniasari </li><li> Team leader of Information Systems (SYS)</li></ul><ul></ul>"

in android just showing two bullets but in ios show trhee bullets like the picture below.

please help.
thanks.

![Capture1](https://user-images.githubusercontent.com/17444704/56725994-1eae8100-6778-11e9-8ca3-a663c9d5483d.PNG)

**Comment by matteobortolazzo** [comment]
Hi, I have no way to test iOS now.
iOS HTML list rendering in native, I cannot do anything about that.
However, looking at your HTML code (I needed to click on EDIT), you have an empty UL, try to remove that.
