### ISSUE TITLE
Custom font not working

### ISSUE THREAD

**Issue by csteeg** [matteobortolazzo/HtmlLabelPlugin#58]
I'm using an embedded font, but the HtmlLabelRenderer does not render it correctly (uses default font instead).
After reading https://stackoverflow.com/questions/19921972/parsing-html-into-nsattributedtext-how-to-set-font I modified LabelHtml.Forms.Plugin.iOS.LabelRendererHelper.SetFontFamily from:
`_builder.Append($"font-family: '{_label.FontFamily}'; ");`
to 
`_builder.Append($"font-family: '-apple-system', '{_label.FontFamily}'; ");`
And my custom font was working just fine. Seems -apple-system is needed since iOS 9

**Comment by PaulsonMac** [comment]
Fon not working in iOS.

**Comment by matteobortolazzo** [comment]
Hi @csteeg ,
can you create a pull request with the update, please?

**Comment by PaulsonMac** [comment]
@csteeg, works fine...

**Comment by csteeg** [comment]
@matteobortolazzo Will do on Monday .. was planning to yesterday, but didnt get to it

**Comment by matteobortolazzo** [comment]
@csteeg No problem, thank you very much for the help

**Comment by matteobortolazzo** [comment]
[3.0.2.3](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/3.0.2.3) Released.

**Comment by benazir46** [comment]
I still have Issues with custom fonts. I added custom fonts following [Xamarin doc](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#use-a-custom-font). Basically, I added Google's Roboto fonts on the shared project and added the reference on the iOS and Android assembly files.

I'm using:

- Xamarin Forms 4.6.0.726
- Xamarin Essentials:  1.5.3.1
- This plugin version 4.1.2

I have also noticed an empty \<p>\</p> acts differently on iOS and Android; iOS adds extra new lines. 

Should I create a new issue with these?

**Comment by 0mpurdy** [comment]
I'm also still having this issue on iOS, worked around it by adding a bindable property for a base64 font face and updating RendererHelper to add it to a style tag on the label, but hoping there is a better way!

**Comment by matteobortolazzo** [comment]
@benazir46 sorry, I completely miss your comment!
@0mpurdy I am reopening this but I cannot work on a release for at least another month...

**Comment by matibak** [comment]
> I still have Issues with custom fonts. I added custom fonts following [Xamarin doc](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#use-a-custom-font). Basically, I added Google's Roboto fonts on the shared project and added the reference on the iOS and Android assembly files.
> 
> I'm using:
> 
> * Xamarin Forms 4.6.0.726
> * Xamarin Essentials:  1.5.3.1
> * This plugin version 4.1.2
> 
> I have also noticed an empty <p></p> acts differently on iOS and Android; iOS adds extra new lines.
> 
> Should I create a new issue with these?

Did you use font name defined in .ttf file for iOS or its filename?

**Comment by matteobortolazzo** [comment]
v5 Released.
