### ISSUE TITLE
UpdateText Error

### ISSUE THREAD

**Issue by muhammetsahin** [matteobortolazzo/HtmlLabelPlugin#6]
Hi,

I'm using HTML Label plugin xamarin forms and 2.0 version. but i've got this error on Android 5.0:

HtmlLabelRenderer.UpdateText ()
Java.Lang.LinkageError: no static method "Landroid/text/Html;.fromHtml(Ljava/lang/String;I)Landroid/text/Spanned;"

no static method "Landroid/text/Html;.fromHtml(Ljava/lang/String;I)Landroid/text/Spanned;"
1
ExceptionDispatchInfo.Throw ()
2
JniEnvironment+StaticMethods.GetStaticMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature)
3
JniType.GetStaticMethod (System.String name, System.String signature)
4
JniPeerMembers+JniStaticMethods.GetMethodInfo (System.String encodedMember)
5
JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters)
6
Html.FromHtml (System.String source, Android.Text.FromHtmlOptions flags)
7
HtmlLabelRenderer.UpdateText ()
8
HtmlLabelRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
9
VisualElementRenderer`1[TElement].SetElement (TElement element)
10
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
11
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
12
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
13
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
14
VisualElementPackager.Load ()
15
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
16
VisualElementRenderer`1[TElement].SetElement (TElement element)
17
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
18
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
19
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
20
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
21
VisualElementPackager.Load ()
22
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
23
VisualElementRenderer`1[TElement].SetElement (TElement element)
24
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
25
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager, Android.Content.Context context)
26
FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState)
27
Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState)
28
(wrapper dynamic-method) System.Object:c7d97a47-b322-438a-9d09-7c539f1bf6bc (intptr,intptr,intptr,intptr,intptr)
29
java.lang.NoSuchMethodError: no static method "Landroid/text/Html;.fromHtml(Ljava/lang/String;I)Landroid/text/Spanned;"
30
md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
31
md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
32
android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
33
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
34
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
35
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
36
android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
37
android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
38
android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
39
android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
40
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
41
android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
42
android.os.Handler.handleCallback(Handler.java:815)
43
android.os.Handler.dispatchMessage(Handler.java:104)
44
android.os.Looper.loop(Looper.java:194)
45
android.app.ActivityThread.main(ActivityThread.java:5536)
46
java.lang.reflect.Method.invoke(Native Method)
47
java.lang.reflect.Method.invoke(Method.java:372)
48
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
49
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by matteobortolazzo** [comment]
Sorry, I just released 2.0.1 that should fix the bug. I have no Lollipop to test. Nuget [HtmlLabel 2.0.1](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.0.1)
