### ISSUE TITLE
Additional library weight due to new references?

### ISSUE THREAD

**Issue by Sebastian1989101** [matteobortolazzo/HtmlLabelPlugin#61]
When updating from 3.0.2.2 to 3.0.2.3 this library now wants to add additional binaries. Is this really necessary? Because for me it just looks like additional weight to the app. 

The following binaries are added in this update: 
- Microsoft.CodeAnalysis.FxCopAnalyzers.2.9.1
- Microsoft.CodeAnalysis.VersionCheckAnalyzer.2.9.1 
- Microsoft.CodeQuality.Analyzers.2.9.1 
- Microsoft.NetCore.Analyzers.2.9.1
- Microsoft.NetFramework.Analyzers.2.9.1

**Comment by matteobortolazzo** [comment]
Hi, 
you are absolutely right, 
I'll try to remove those when I have free time this weekend
