### ISSUE TITLE
Style for font color in rgb is not working for android

### ISSUE THREAD

**Issue by sparikhassurecare** [matteobortolazzo/HtmlLabelPlugin#62]
Hello,

I am having two issues regarding Android font color.

Issue 1: 
I am trying below Html with HtmlLabelPlugin, and it is not showing font color for Android, but it does for iOS.

`<p><span style=\"color: rgb(230, 0, 0);\">Red</span><span style=\"color: rgb(0, 102, 204);\"> Blue </span><span style=\"color: rgb(0, 138, 0);\">Green</span></p>`

If I replace rgb color to Hex code, it will work for both. 

Issue 2:
If html has style tag inside `<strong> `then android will not display font color, but iOS does.

`<p><strong style=\"color: #008A00;\">Bold Green</strong></p>`

**Comment by matteobortolazzo** [comment]
Hi @sparikhassurecare,
unfortunately those issues are not related to the plugin but with the native rendering of Android so I cannot help you with this.
I'm really sorry.
