### ISSUE TITLE
UWP style doesn't work?

### ISSUE THREAD

**Issue by mzhukovs** [matteobortolazzo/HtmlLabelPlugin#63]
Hey, 

Great plug-in, thanks for the effort.

This might be known/intentional, but it wasn't 100% clear to me in the readme so thought I'd ask: on UWP - are the ONLY html elements supported those basic tags listed there? I see when I attempt to apply a basic color style via a span, it does not render. The HTML tags are removed and the label just displays the remaining, plan text, without the color applied.

For example, this does not come out green in UWP:

        <htmlbl:HtmlLabel
            HorizontalTextAlignment="Center"
            Text="&lt;span style=&quot;color:green&quot;&gt;&lt;b&gt;I am bold html text in a span, but on UWP I'm not green :( &lt;/b&gt;&lt;/span&gt;" />

but it does on Android.

Am I missing something? I am using v3.0.2.2 of the plugin and have the following in my UWP project's App.xaml.cs:
```
                var assembliesToInclude = new List<Assembly>
                {
                    /* In general, third party components cannot be viewed in UWP when the project is built in release mode when
                        * the .Net Native tool chain (project->Build ->Compile with Native Tool chain) is enabled.
                        * To view the controls in release mode, we must pass the custom renderer assemblies to the XF Init method as follows */
                    typeof(HtmlLabelRenderer).GetTypeInfo().Assembly
                };
                Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```

**Comment by matteobortolazzo** [comment]
Hi @mzhukovs,
so UWP do not support HTML, I just parse the HTML and create a [RichTextBlock](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/rich-text-block) so style do not work. To support UWP css must be parsed and converted in UWP properties.
I'm sorry

**Comment by mzhukovs** [comment]
Thanks for the quick response @matteobortolazzo - I think I'll just switch to WebView for everything then. This has the added benefit of letting users select and copy text to their clipboard on their devices too.

For any that are curious, just use the converter below and this will render all html elements including any style tags and works on UWP too:

        <WebView
            HeightRequest="200"
            Source="{Binding
                YourHtmlString,
                Converter={StaticResource HtmlSourceConverter}}"
            WidthRequest="400" />

```
    public class HtmlSourceConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var html = new HtmlWebViewSource();

            if (value != null)
            {
                html.Html = value.ToString();
            }
            else
            {
                html.Html = "";
            }
            return html;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
```
