### ISSUE TITLE
Font color not working in iOS

### ISSUE THREAD

**Issue by alexthekid07** [matteobortolazzo/HtmlLabelPlugin#64]
I am trying to set an HtmlLabel to have a font color and it doesn't seem to be working in iOS...
`returnMsg.DeliveryText = "<span style='color: #008000;'>&#10004;</span>";`

It doesn't work with "color: green;" either. Am I doing something wrong or does this not work with special characters like a checkmark?

**Comment by matteobortolazzo** [comment]
Hi @alexthekid07,
this plugin just call the native HTML rending for label in iOS.
Personally I don't know the answer, it seems correct. 
Try to give a look to the native docs.
I'm sorry.
