### ISSUE TITLE
Inline styling

### ISSUE THREAD

**Issue by Nanouz** [matteobortolazzo/HtmlLabelPlugin#65]
Hi,

I am using your plugin and it works but I can't seem to use inline styling like this :

```
public string BodyStyled => $"<!DOCTYPE html>" +
                                    $"<html>" +
                                        $"<head>" +
                                            $"<style>" +
                                                $"p {{ margin-bottom: 5px; }}" +
                                            $"</style>" +
                                        $"</head>" +
                                        $"<body>" +
                                            $"{Body}" +
                                        $"</body>" +
                                    $"</html>";
```
```
                    <htmlLabel:HtmlLabel
                        Grid.Row="0"
                        VerticalOptions="Center"
                        TextColor="{ DynamicResource BaseTextColor }"
                        Text="{ Binding Detail.BodyStyled }"/>
```

The style : p { margin-bottom: 5px; } gets printed above the text.

How can I achieve this?
Thx!

**Comment by matteobortolazzo** [comment]
Hi, 
this is a label not a webview, it's not possible to use <style> blocks sorry.
Not a plugin limitation but a native limitation.

The easiest thing to to is can be pre-process the HTML input. 
`body = body.Replace("<p>",  "<p style=\"margin-bottom: 5px\"");`
Or something like that.

But to be honest if you have a big body, use a WebView...
And use Label margin property not the CSS one.
