### ISSUE TITLE
Problema con style

### ISSUE THREAD

**Issue by acaliaro** [matteobortolazzo/HtmlLabelPlugin#66]
Ciao Matteo

ti scrivo in italiano...

`        public string HtmlString { get; set; } = @"<span style=""background:red;"">COLOR</span><u>Some underlined text</u> Upon sign in you agree to our <a href=""http://www.infernored.com"">Terms of Service</a> and <a href=""http://www.infernored.com"">Privacy Policy</a>.";`

se utilizzo questa stringa in binding con il tuo controllo, funziona tutto tranne lo "style"... dove è che sbaglio?

`            <htmlLabel:HtmlLabel Text="{Binding HtmlString}"/>
`

Grazie
Alessandro

**Comment by matteobortolazzo** [comment]
Ciao, se metti la stringa direttamente funziona? Non so se background è supportato.

**Comment by acaliaro** [comment]
Ciao

No, sembra che non applichi nulla all’interno di style, temo sia una limitazione di Android

**Comment by matteobortolazzo** [comment]
Cose base come "color" dovrebbero funzionare anche su Android.

**Comment by acaliaro** [comment]
<span style="color:blue;">This is a Blue Heading</span>

questo non colora, rimane la scritta nera

**Comment by acaliaro** [comment]
public string HtmlString { get; set; } = "<a>This is a  <font color='#0000FF'> blue text</font> and this is a <font color='red'> red text</font> </a>";

questo funziona...

**Comment by matteobortolazzo** [comment]
Non ti so dire, non ho altri issue aperti per problemi col CSS, io stesso non ho avuto problemi con i colori. Non so cosa possa essere. Forse il binding?

**Comment by acaliaro** [comment]
Tranquillo, con xf4.3 Label gestisce anche html e la stringa che ti ho postato viene visualizzata correttamente. Utilizzo quello ufficiale... grazie
