### ISSUE TITLE
Links Styling not working

### ISSUE THREAD

**Issue by sereoja** [matteobortolazzo/HtmlLabelPlugin#67]
Hi,
I am trying to simple remove decorations and it doesn't work.
<a href="https://www.google.com/" style="text-decoration: none;">Google</a>
any solutions?

**Comment by matteobortolazzo** [comment]
Hi, sorry for the late response.
I didn't work on this for months.
Does this happens on both platform?
I rely on native HTML label rendering, so it could be simply not possible.

**Comment by matteobortolazzo** [comment]
Support for LinkColor and LinkUnderline support with next release.
[https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/6077639b728eed8468f8567936a1ce5d9883ba6a](https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/6077639b728eed8468f8567936a1ce5d9883ba6a)

**Comment by matteobortolazzo** [comment]
Fix iOS bug [https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/409859c0142bea5a9584f3247d2e4e8d26dd5825](https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/409859c0142bea5a9584f3247d2e4e8d26dd5825)

**Comment by matteobortolazzo** [comment]
Closed with #80
