### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by ludas96** [matteobortolazzo/HtmlLabelPlugin#68]
Is it possible to make the HtmlLabel selectable by the user? Like by using a longpress/double tap on the text, the word would be selected.

Currently this is not possible to do with Labels as they don't support selectable - this could be done however, using Editor or Entry. So if it's possible to remake this plugin with Editor instead of Label, that would be great.

**Comment by matteobortolazzo** [comment]
Hi, unfortunately it is not possible because underneath it uses Android's TextView and iOS's UiLabel. Editors don't have the ability to display HTML.
