### ISSUE TITLE
iOS: ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by t30n3** [matteobortolazzo/HtmlLabelPlugin#69]
Ciao Matteo,
sto cercando di pubblicare la mia app che utilizza il tuo plug-in e in fase di approvazione l'App Store Connect mi ritorna il seguente "errore":

**ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.**

Visto che non trovo riferimenti all'interno del mio codice di queste API, immagino siano utilizzate dal tuo plug-in. Puoi gentilmente verificare?

Grazie mille,
Matteo

**Comment by matteobortolazzo** [comment]
Ciao,

sicuro sia colpa del mio plugin?
Io non uso la WebView https://github.com/matteobortolazzo/HtmlLabelPlugin/blob/dev/src/HtmlLabel/Renderer.ios.cs

**Comment by t30n3** [comment]
In realtà no, visto di cosa si trattava immaginavo fosse il tuo plug-in.
Grazie della conferma, cercherò negli altri oggetti.
