### ISSUE TITLE
[Suggestion] Make links work

### ISSUE THREAD

**Issue by TGlev** [matteobortolazzo/HtmlLabelPlugin#7]
Hi!

I'm using your plugin and I would love it if you could make `<a href="www.google.com" />` work! You could make it use Device.OpenUri("");

Thanks for the amazing plugin!

-Luca

**Comment by matteobortolazzo** [comment]
Thanks for the suggestion, I'll do it as soon as I can

**Comment by TGlev** [comment]
Would be greatly appreciated!

**Comment by matteobortolazzo** [comment]
Try the new version [2.1.0](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.1.0)

**Comment by TGlev** [comment]
`<p>In gesprek met Zane Lowe van <a href=\"https://www.youtube.com/watch?v=VswT01nKLLA\" target=\"_blank\">Beats1</a> zegt de zanger dat hij voor zijn optreden tijdens de rust van de American Football-finale een les trekt uit het voorval uit 2004.`

Im using this HTML, and it does make the URL blue and underlined, but nothing happens when I press it. 

Im testing it on an iOS Simulator. Havent been able to test it on an actual iOS device or android device, would this solve the problem?

**Comment by matteobortolazzo** [comment]
Now I don't have a Mac to test but it should work, on Android it works fine. Please try on a real ios device and let me know

**Comment by TGlev** [comment]
I tried it, on both iPhone and an android phone. Both were real phones, the links did not work.

**Comment by matteobortolazzo** [comment]
Very strange on my android 7.0 it works. I'll check on other devices

**Comment by heatgithub** [comment]
My tests gives the same result. Works on a real Android device and in UWP, not in the iOS simulator. Didn't test on a real iOS device.

**Comment by TGlev** [comment]
I still can't get it to work on an actual Android device. Even not one with android 7.0

**Comment by matteobortolazzo** [comment]
It's not working on iOS, I'll try to make it works

**Comment by matteobortolazzo** [comment]
Ok with [2.1.1](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.1.1) it works on iOS, it has been a nightmare... Let me know

**Comment by matteobortolazzo** [comment]
Sorry 2.1.2 is the right one

**Comment by TGlev** [comment]
Can confirm it works on iOS. Have yet to test it on an android device.

Thanks for implementing this, it's really appreciated! :D

**Comment by matteobortolazzo** [comment]
:D 
I tested it on an LG G3 7.1 (LineageOS) and an LG G6 with 7.0 (Stock) and it works on both

**Comment by stepanic** [comment]
For me, it works on iOS on simulators and devices but on the Android links do not work, I tested on the Android Emulator Nexus 5 (Android 7.1.1) and on the device Huawei P9 (Android 7.0)
