### ISSUE TITLE
Arabic Text Aligned Issue

### ISSUE THREAD

**Issue by quantumarun** [matteobortolazzo/HtmlLabelPlugin#70]
When using HTMLLabel for Arabic the alignment is not proper. The text characters are swapped example .(dot) comes to the right side instead of at the end of the sentence(left side). As Arabic is RTL language. Can you check on this?

**Comment by matteobortolazzo** [comment]
Hi, does this happen on both Android and iOS?

**Comment by quantumarun** [comment]
Yes.
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-08 at 15 30 30](https://user-images.githubusercontent.com/5046311/70412452-4b48ac00-1a6e-11ea-8527-a252da25dbcc.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-09 at 09 56 16](https://user-images.githubusercontent.com/5046311/70412453-4b48ac00-1a6e-11ea-81ed-f551fe35a861.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-09 at 09 56 30](https://user-images.githubusercontent.com/5046311/70412456-4b48ac00-1a6e-11ea-8edc-fb3277bb3e8d.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-09 at 09 57 58](https://user-images.githubusercontent.com/5046311/70412457-4be14280-1a6e-11ea-879e-12f04a198867.png)

**Comment by quantumarun** [comment]
Any luck with this? Quite important for us now for the fix.

**Comment by matteobortolazzo** [comment]
Hi sorry,
do you have any documentation on how to achieve this?
Also, how can I test it?

**Comment by matteobortolazzo** [comment]
I will work on this with the next release (I will close a bunch of issues).
Then I just need to help to test it.

**Comment by quantumarun** [comment]
By the way this happens on iOS only. Works fine on Android. Do you have any ETA on this?

**Comment by matteobortolazzo** [comment]
Hi, I am actively working on the plugin. So I hope no more than 2 weeks. I will try to close also other opened issues.
Can you send me an text I can use to test?

**Comment by matteobortolazzo** [comment]
Fixed in [https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/7b44ec19eabcdffc72be7d6c000fec8ca02fb1e0](https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/7b44ec19eabcdffc72be7d6c000fec8ca02fb1e0)

![arab](https://user-images.githubusercontent.com/15217470/76153911-635eb480-60cb-11ea-9434-f05139fbb7a7.png)

**Comment by quantumarun** [comment]
When will this be available on nuget store? Also for English the dot(.) should be on right.

**Comment by matteobortolazzo** [comment]
I will create a preview package soon.
I will check the dot for English too

**Comment by matteobortolazzo** [comment]
But, do you have Arabic and English at the same time?

**Comment by matteobortolazzo** [comment]
What should be the behavior of English text on RTL phones? Align to the right with dot on the right too?

**Comment by matteobortolazzo** [comment]
Improved behavior. [https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/8766bd30e32651ca4a1ee7920af63a344f9d14b1](https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/8766bd30e32651ca4a1ee7920af63a344f9d14b1) 

![2020-03-08_07-46-03-PM](https://user-images.githubusercontent.com/15217470/76170114-c78a8280-6176-11ea-8d07-2568ce1c8ad6.png)

**Comment by quantumarun** [comment]
Based on the Language the Alignment should be set. So if its arabic then English and Arabic both should be on Right side(RTL). Yes, there could be english text also in case of RTL due to some constraints. The first screen you shared was correct only the dot (.) in english should be on the right.
Can you share the nuget package by today?

**Comment by matteobortolazzo** [comment]
Then, it behave correctly but not in Android. The dot is in the right place, but the alignment is based on the content, not the device language. And I am trying to forcing it like for iOS but it's not working. For center alignment there should be no problem tho. I can create a NuGet if you really need it.

**Comment by quantumarun** [comment]
We are using center as well as Start alignment. I was working on an issue with microsoft team and to achieve this we kept the FlowDirection as LeftToRight but changed the Alignment based on the Language so for English the Alignment was Start and for Arabic it was End if it helps in anyway, Yes you can create the Nuget and we can enhance based on my testing as well.

**Comment by matteobortolazzo** [comment]
Try this one and let me know [https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/4.0.0-preview.1](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/4.0.0-preview.1)

**Comment by matteobortolazzo** [comment]
@quantumarun does it work as expected?

**Comment by matteobortolazzo** [comment]
Can I close this one then?

**Comment by matteobortolazzo** [comment]
Closed with #80
