### ISSUE TITLE
Anchor Tag Problem

### ISSUE THREAD

**Issue by uysuy** [matteobortolazzo/HtmlLabelPlugin#71]
When I was tried with Anchor tag it error with URL
Please make it like browser that we can use anchor tag 

Thanks

**Comment by matteobortolazzo** [comment]
If you want a browser just use a WebView.
Labels are not suppose to do that.
You can implement a custom event on link click and scroll the page yourself.
Also I cannot do anything, it's a limitation on the native controls.
