### ISSUE TITLE
MaxLines and LineBreakMode are not working

### ISSUE THREAD

**Issue by MohanaSundharamMurugan** [matteobortolazzo/HtmlLabelPlugin#73]
This is my code in xaml, but the result i got multiline label and it looks like scrollable. I want the result like "abcdefgh..."

<htmlLabel:HtmlLabel htmlLabel:HtmlLabel.MaxLines="1" TextType="Html" LineBreakMode="TailTruncation" FontFamily="{StaticResource Lato-Light}" FontSize="20" Text="{Binding Item_Name_HTML}"></htmlLabel:HtmlLabel>

**Comment by matteobortolazzo** [comment]
Hi, on which platform?

**Comment by matteobortolazzo** [comment]
BTW Set TextType="Html" disables my implementation

**Comment by matteobortolazzo** [comment]
Hi, I tried to find a solution to this. But I think it's a limitation with HTML in Labels. Sorry, I cannot find a solution to this.
