### ISSUE TITLE
Feature: Simplify Html

### ISSUE THREAD

**Issue by AlexSchuetz** [matteobortolazzo/HtmlLabelPlugin#77]
I am displaying html-texts, that were generated by some WYSIWYG-Editors.
Unfortunately the HTML contains following problems, that cause really ugly output:
- empty paragraphs
- additional `<br />` tags after `</li>` or `</p>` tags

One additional problem is, that after lists the text continues without spacing to the list, which doesn't look very nice either.

I implemented some methods to beautify the html, controlled by a bindable property.

If you like I would prepare a PR to add this feature to the plugin.

**Comment by matteobortolazzo** [comment]
Sure, let me refactor existing code a bit since it's month I don't work on it, then you can branch and add you code :)

**Comment by matteobortolazzo** [comment]
Hi @AlexSchuetz I refactored the project and the shared file. I finally added unit tests for shared code too. So if you want you can prepare a PR from the dev branch while I refactor and test platform-specific code :)

**Comment by matteobortolazzo** [comment]
Closing this. Please open a PRs if needed. But I think you should clear you string before feeding it to the label. Different people have different needs and this will not suite everybody.
