### ISSUE TITLE
TapGestureRecognizer not working on android

### ISSUE THREAD

**Issue by AlexSchuetz** [matteobortolazzo/HtmlLabelPlugin#78]
If you register a TapGestureRecognizer on the HtmlLabel it will work on iOS but not on android.

**Comment by matteobortolazzo** [comment]
Fixed in [https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/08c20cc6a4decfd19c39769f2a9fa2ec4235b9db](https://github.com/matteobortolazzo/HtmlLabelPlugin/commit/08c20cc6a4decfd19c39769f2a9fa2ec4235b9db) (But it disables links)

**Comment by matteobortolazzo** [comment]
Dublicate of [https://github.com/matteobortolazzo/HtmlLabelPlugin/issues/35](https://github.com/matteobortolazzo/HtmlLabelPlugin/issues/35)
