### ISSUE TITLE
Upgrade causing LabelHtml.Forms.Plugin.UWP to not be found in UWP project.

### ISSUE THREAD

**Issue by Surfrat** [matteobortolazzo/HtmlLabelPlugin#85]
Hi,

Just upgraded from 3.0.2.2 to 4.1.0.

Old version is working. With new version I cannot build as I get this in UWP\App.xaml.cs:

1. Error	CS0234	The type or namespace name 'UWP' does not exist in the namespace 'LabelHtml.Forms.Plugin' 

2. Error	CS0246	The type or namespace name 'HtmlLabelRenderer' could not be found

I have completely removed and re-installed the library using Nuget.

It appears to be installed correct in UWP:
![image](https://user-images.githubusercontent.com/2066487/77642121-cf636880-6f65-11ea-9195-9b5293de961c.png)

Any ideas as to a fix.

Thanks

Mark.

**Comment by matteobortolazzo** [comment]
I think you are targeting something older that `17763`, try to target. If you cannot do that keep 3x since Microsoft is pushing 17763

**Comment by Surfrat** [comment]
Thanks for the quick reply. That put me on the right track... it was the min version.

Original:
![image](https://user-images.githubusercontent.com/2066487/77643741-8f51b500-6f68-11ea-949e-429da6b50185.png)

New:
![image](https://user-images.githubusercontent.com/2066487/77643882-ca53e880-6f68-11ea-86b3-7a10ecbf7155.png)


Thank you.

**Comment by matteobortolazzo** [comment]
Great, glad to hear that
