### ISSUE TITLE
FontSize issue on iOS

### ISSUE THREAD

**Issue by sereoja** [matteobortolazzo/HtmlLabelPlugin#86]
Hi,
noticed today that FontSize="16" renders a wrong size on iPhone 11 emulator. On Android it look ok, but not on iOS. The rendering it looks like it goes to Small size instead of 16. I tried other sizes like 20, 17, 15, and 14 and it looks like it renders properly but it has issue with font size 16.
Thx

I have latest update of plugin, Xamarin.Forms and visual studio on mac.

**Comment by matteobortolazzo** [comment]
Hi, was it working properly with 3.x.x?

**Comment by sereoja** [comment]
Yes it was working properly before. Suddenly after the update I noticed all my labels got extra small , so I looked that every label that had FontSize = 16 had this issue. I then had to change to 17 or 15 to get close to what I needed but 16 would not work anymore.

**Comment by matteobortolazzo** [comment]
Sorry, I don't get the issue.
16 is the default size and so, the size of 16 and "nothing" is the same.
Am I missing something?

![fontsize](https://user-images.githubusercontent.com/15217470/78185098-75c9d500-7462-11ea-9121-a53388a11278.PNG)

**Comment by sereoja** [comment]
Try a label with 15, a label with 16 and a label with 17 and compare them side by side

**Comment by sereoja** [comment]
> Sorry, I don't get the issue.
> 16 is the default size and so, the size of 16 and "nothing" is the same.
> Am I missing something?
> 

Why your label and htmlLabel visually on the emulator are of different sizes?
![img](https://user-images.githubusercontent.com/19211452/78188360-efdb6900-7424-11ea-9968-d5b0fd895626.png)

**Comment by matteobortolazzo** [comment]
Because I need to stop doing this stuff when I should sleep ahah
I will give a look tonight tho

**Comment by matteobortolazzo** [comment]
Fixed with  4880baf

**Comment by sereoja** [comment]
It looks like the fix is for padding on the bottom of the label, but this thread is on font size 16. or am I missing something?

**Comment by matteobortolazzo** [comment]
My bad, fixed with 4c677f4
