### ISSUE TITLE
Padding issue with <html>

### ISSUE THREAD

**Issue by sereoja** [matteobortolazzo/HtmlLabelPlugin#87]
Hi,
On both platforms I get this issue where the string in html tags creates that extra padding on the bottom of the htmlLabel.
In the image attached I assigned backgroundcolor of the htmlLabel to green, and you can see that it created extra space on the bottom.
here is the code for this layout
<htmlLabel:HtmlLabel 
                            BackgroundColor="Green"
                            TextColor="Black"
                            Margin="5"
                            FontSize="15"
                            Navigating="Handle_Navigating"
                            VerticalOptions="CenterAndExpand"
                            HorizontalOptions="CenterAndExpand"
                            HorizontalTextAlignment="Center"
                            VerticalTextAlignment="Center"
                            Text="{Binding TileItems.HTMLBelowTitle}"/>

![image](https://user-images.githubusercontent.com/19211452/77952903-3db76c00-7281-11ea-897e-ef50dfa45acb.png)

**Comment by erismamn** [comment]
Hi,
I experience the same problem (v4.1.0). It seems to me like an extra '\n' is (still there) in the TextView's Text-property i Android. I temporarily solved it by making an inherited HtmlLabelEx and in it's inherited renderer replaced the ending '\n' in OnElementPropertyChanged after calling it's base:
`                if (Control.Text.EndsWith('\n'))
                {
                    Control.Text = Control.Text.TrimEnd('\n');
                }
`

**Comment by matteobortolazzo** [comment]
Strange, the code to remove the last "\n" is in place. I will check again
