### ISSUE TITLE
Inline Styling not working

### ISSUE THREAD

**Issue by sereoja** [matteobortolazzo/HtmlLabelPlugin#89]
Unfortunately could not get inline styling to work on iOS and Android, can anyone reproduce? 
`<h1 style="font-size: 24pt; font-weight: bold; color: #8c191c;">Welcome</h1>`
`<p style="font-size: 13pt; font-weight: bold; color: #8c191c;">Our favorite family tradition</p>`

**Comment by sereoja** [comment]
I also detected issues with other type of styling such as <big><strong>
for example:
before I had: <p>Some say it was a 17<sup>th</sup> century... </p> and th was properly rendered elevated but now either on Android or iOS these are not working.

**Comment by matteobortolazzo** [comment]
Hi, 
yes it does render correctly (in master).
Here the list of supported tags/styles [https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling](https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling)
