### ISSUE TITLE
LineHeight available but not supported?

### ISSUE THREAD

**Issue by sereoja** [matteobortolazzo/HtmlLabelPlugin#90]
I can see the parameter LineHeight is available in xaml but when setting a value it doesn't work. I checked the list of supported parameters in description and this one is not supported. Would be nice to have. doe's anyone know how to implement this on iOS and Android via Custom Renderer?

**Comment by matteobortolazzo** [comment]
Hi, it's possible to implement it. However LineHeight does not work in Android even with the default Label.
