### ISSUE TITLE
mailto links are not working for versions >v4.0.0

### ISSUE THREAD

**Issue by christianrr** [matteobortolazzo/HtmlLabelPlugin#92]
For me, mailto-Links are not working in Android for versions above 4.0.0. However, it works for 3.0.2.2.
Instead of the full e-mail it just inserts //domain.com into the To field of the mail client.

Tested in Android 10.

**Comment by matteobortolazzo** [comment]
Hi, there is an issue with Xamarin.Essential. I will check if there is a workaround.

**Comment by BomarEloria** [comment]
any luck yet?  I am having the same issue
