### ISSUE TITLE
HTML tel: & mailto: works on Android but not iOS

### ISSUE THREAD

**Issue by minahenin** [matteobortolazzo/HtmlLabelPlugin#93]
First I'd like to thank you so much for the plugin, it's very useful

Here is my issue:
the below works fine in Android but not iOS

<a href="tel:1234567890">(123)456-7890</a> or <a href="mailto:email@server.com" target="_top">email@server.com</a>

**Comment by minahenin** [comment]
Looks like Git is parsing the HTML to attaching it as image

**Comment by BomarEloria** [comment]
I am having the same issue

**Comment by matteobortolazzo** [comment]
@minahenin are you sure it works on Android?
BTW it's a limitation of xamarin essential.
I have to parse the URL and handle those cases manually

**Comment by matteobortolazzo** [comment]
The fix will be in 4.1.2 let me know

**Comment by minahenin** [comment]
> The fix will be in 4.1.2 let me know

Thank you so much, it works well in iOS now, just had to add tel & mailto to the info.plist LSApplicationQueriesSchemes, maybe we need to update the documentation 
Again Thx a lot :)

**Comment by matteobortolazzo** [comment]
Glad to hear, but strange, Xamarin.Essential doesn't mention any info.plist change for that

**Comment by BomarEloria** [comment]
It is working for me and I didn’t change anything other than upgrade the plugin
