### ISSUE TITLE
htmlLabel:HtmlLabel type not found

### ISSUE THREAD

**Issue by vmsJenni** [matteobortolazzo/HtmlLabelPlugin#94]
Added the nuget package, and followed instructions for usage (xaml)
MainPage.xaml does not find htmlLabel:HtmlLabel;
<htmlLabel:HtmlLabel Text="HtmlLabel" />

Tried Clean Solution / restarted VS /  removed/re-installed nuget pkg... still not found?

project:
Xamarin Forms ios (cross platform project)
Xam.Plugin.HtmlLabel 4.1.1
Xamarin.Essentials 1.5.2
Xamarin.Forms 4.5.0,617

**Comment by matteobortolazzo** [comment]
Hi,
did you add `xmlns:htmlLabel="clr-namespace:LabelHtml.Forms.Plugin.Abstractions;assembly=HtmlLabel.Forms.Plugin"`?

**Comment by vmsJenni** [comment]
Apologies for delay in response - yes, I have (had) that  configured.
Just updated nuget pkg to 4.1.2 - same issue as before;

The type 'htmlLabel:HtmlLabel' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.


[MainPage.xaml.txt](https://github.com/matteobortolazzo/HtmlLabelPlugin/files/4541158/MainPage.xaml.txt)

**Comment by matteobortolazzo** [comment]
That's strange! It should work. You are the only one with this issue.

Can you clone the repo and try the test app and let me know?

**Comment by vmsJenni** [comment]
Matteo,

I found the problem - the nuget pkg was only installed onto the ios, and not the shared project - I have it working now - sorry for the confusion.

**Comment by matteobortolazzo** [comment]
Don't worry, glad to hear you solved it!
