### ISSUE TITLE
HtmlLabelRenderer not found in UWP apps

### ISSUE THREAD

**Issue by corpdev** [matteobortolazzo/HtmlLabelPlugin#96]
I installed the latest build, 4.1.2, and tried to add the following lines for UWP (App.xaml.cs)

                var rendererAssemblies = new[] { typeof(HtmlLabelRenderer).GetTypeInfo().Assembly };
                Xamarin.Forms.Forms.Init(e, rendererAssemblies);
                HtmlLabelRenderer.Initialize();

However, I can't resolve the namespace for the HTMLLabelRenderer.  
Thanks

**Comment by matteobortolazzo** [comment]
Which version of UWP are you targeting?

**Comment by corpdev** [comment]
Target Version 18362.  Min version 16299

**Comment by corpdev** [comment]
Thank you,  I changed the min version to 17763; and things are up and running.  Thanks again for the help.   I wouldn't have thought of trying that.

**Comment by matteobortolazzo** [comment]
My bad, I will update the README
