### ISSUE TITLE
Make tap/click area for links bigger

### ISSUE THREAD

**Issue by hellyeahniels** [matteobortolazzo/HtmlLabelPlugin#98]
Is it possible to enlarge the clickarea for links? When the text is small, you have to tap precisely on the link. Sometimes I need to tap several times with my big fingers.

I know the styling is not fully supported, but I tried something like this anyways, but it didn't work:

`<a href="http://www.google.com/" style="display: inline-block; position: relative; z-index: 1; padding: 10px; margin: -10px;">click</a>`

I tried this on an iPhone.

It is possible to add this functionallity or is there another way to accomplish this?

**Comment by matteobortolazzo** [comment]
Hi, 
you can play with this class
https://github.com/matteobortolazzo/HtmlLabelPlugin/blob/master/src/HtmlLabel/iOS/LinkTapHelper.cs

However, do browsers do that? I mean, if you tap the wrong place is makes sense that it's not going to work

**Comment by hellyeahniels** [comment]
Ok nice, I'll take a look at that. And yeah, it's possible with this styling. 

![image](https://user-images.githubusercontent.com/10339613/80000495-7da6f300-84bd-11ea-9228-628b4f772ba2.png)

If you click the red area, this link works ;)

**Comment by matteobortolazzo** [comment]
Glad to hear, it close this then
