### ISSUE TITLE
Does it support flow direction?

### ISSUE THREAD

**Issue by lbshopping** [matteobortolazzo/HtmlLabelPlugin#99]
Hi,
I am trying to set 
`FlowDirection="{x:Static Device.FlowDirection}"`

to the element itself or the parent elements and even through the code like:

`this.FlowDirection = Device.FlowDirection;`

but it's still displaying it LTR instead of RTL.

**Comment by matteobortolazzo** [comment]
Hi, 
it should work.
Does it happens in both iOS and Android?
Can you provide a screenshot and the desired behaviour?

**Comment by lbshopping** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-04-30 at 10 04 14](https://user-images.githubusercontent.com/64304556/80682055-78076980-8aca-11ea-8789-caee22c723d7.png)
Text flow should be from right to left like any RTL layout.

**Comment by lbshopping** [comment]
I am using code from Microsoft docs which is working for all except this [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left](url)

**Comment by matteobortolazzo** [comment]
Oh ok, so the flow should be automatic based on the language (not on me, it's the native implementation). So it will be on the right for Arabic. Try to set the HorizontalAlignment for English content

**Comment by lbshopping** [comment]
Yes, but it's not working! For English it is displaying properly from Left to Right, but for Arabic, it's not switching to Right to Left.

Here's the code I am using:

` <htmlLabel:HtmlLabel FlowDirection="{x:Static Device.FlowDirection}" FontFamily="{StaticResource BoldFont}" Text="{Binding question}" FontAttributes="Bold" FontSize="16" TextColor="Black" />`

Any clue on what I should do to get it to work?

**Comment by matteobortolazzo** [comment]
Oh ok, that's strange. Can you please clone the repo and start the test app? There is a test label for this. Can you check if it behave the same? (I don't have a Mac with me right now). But I am pretty sure it was working as expected

**Comment by matteobortolazzo** [comment]
No follow, closing this
